// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, implicit_dynamic_list_literal, implicit_dynamic_map_literal, inference_failure_on_collection_literal

import 'package:mason/mason.dart';

final analyticsRoleBundle = MasonBundle.fromJson(<String, dynamic>{
  "files": [
    {
      "path": "lib/core/analytics/analytics_service.dart",
      "data":
          "Ly8vIFJlY29yZHMgd2hhdCB1c2VycyBkbyBpbiB0aGUgYXBwLgphYnN0cmFjdCBpbnRlcmZhY2UgY2xhc3MgQW5hbHl0aWNzU2VydmljZSB7CiAgLy8vIExvZ3MgdGhlIGV2ZW50IFtuYW1lXSB3aXRoIFtwYXJhbWV0ZXJzXS4KICBGdXR1cmU8dm9pZD4gbG9nRXZlbnQoU3RyaW5nIG5hbWUsIHtNYXA8U3RyaW5nLCBPYmplY3Q+PyBwYXJhbWV0ZXJzfSk7CgogIC8vLyBMb2dzIHRoYXQgdGhlIHVzZXIgc2lnbmVkIGluLCB3aXRoIHRoZSBzaWduLWluIFttZXRob2RdLgogIEZ1dHVyZTx2b2lkPiBsb2dTaWduSW4oe1N0cmluZz8gbWV0aG9kLCBNYXA8U3RyaW5nLCBPYmplY3Q+PyBwYXJhbWV0ZXJzfSk7CgogIC8vLyBMb2dzIHRoYXQgdGhlIHVzZXIgc2lnbmVkIHVwLCB3aXRoIHRoZSBzaWduLXVwIFttZXRob2RdLgogIEZ1dHVyZTx2b2lkPiBsb2dTaWduVXAoewogICAgcmVxdWlyZWQgU3RyaW5nIG1ldGhvZCwKICAgIE1hcDxTdHJpbmcsIE9iamVjdD4/IHBhcmFtZXRlcnMsCiAgfSk7CgogIC8vLyBUdXJucyB0aGUgY29sbGVjdGlvbiBvZiBhbmFseXRpY3MgZGF0YSBvbiBvciBvZmYuCiAgRnV0dXJlPHZvaWQ+IHNldEFuYWx5dGljc0NvbGxlY3Rpb25FbmFibGVkKGJvb2wgZW5hYmxlZCk7CgogIC8vLyBTZXRzIHRoZSBpZCBvZiB0aGUgc2lnbmVkLWluIHVzZXIsIG9yIGNsZWFycyBpdCB3aXRoIGBudWxsYC4KICBGdXR1cmU8dm9pZD4gc2V0VXNlcklkKFN0cmluZz8gdXNlcklkKTsKCiAgLy8vIFNldHMgdGhlIHVzZXIgcHJvcGVydHkgW25hbWVdIHRvIFt2YWx1ZV0sIG9yIGNsZWFycyBpdCB3aXRoIGBudWxsYC4KICBGdXR1cmU8dm9pZD4gc2V0VXNlclByb3BlcnR5KHtyZXF1aXJlZCBTdHJpbmcgbmFtZSwgcmVxdWlyZWQgU3RyaW5nPyB2YWx1ZX0pOwp9CgovLy8gUmV0dXJucyB0aGUgYW5hbHl0aWNzIHNlcnZpY2Ugb2YgdGhlIGFwcCwgd2hpY2ggZm9yd2FyZHMgZXZlcnkgY2FsbCB0bwovLy8gdGhlIGFuYWx5dGljcyBzZXJ2aWNlcyBvZiBhbGwgbW9kdWxlcy4KQW5hbHl0aWNzU2VydmljZSBjcmVhdGVBbmFseXRpY3NTZXJ2aWNlKCkgPT4gX2FuYWx5dGljc1NlcnZpY2U7CgpmaW5hbCBBbmFseXRpY3NTZXJ2aWNlIF9hbmFseXRpY3NTZXJ2aWNlID0KICAgIF9BbmFseXRpY3NTZXJ2aWNlcyhfYW5hbHl0aWNzU2VydmljZXMpOwoKe3t7c21mX2FuYWx5dGljc19faW1wbGVtZW50YXRpb25zfX19CgpmaW5hbCBjbGFzcyBfQW5hbHl0aWNzU2VydmljZXMgaW1wbGVtZW50cyBBbmFseXRpY3NTZXJ2aWNlIHsKICBjb25zdCBfQW5hbHl0aWNzU2VydmljZXModGhpcy5fc2VydmljZXMpOwoKICBmaW5hbCBMaXN0PEFuYWx5dGljc1NlcnZpY2U+IF9zZXJ2aWNlczsKCiAgQG92ZXJyaWRlCiAgRnV0dXJlPHZvaWQ+IGxvZ0V2ZW50KFN0cmluZyBuYW1lLCB7TWFwPFN0cmluZywgT2JqZWN0Pj8gcGFyYW1ldGVyc30pID0+CiAgICAgIF9mb3JBbGwoKHNlcnZpY2UpID0+IHNlcnZpY2UubG9nRXZlbnQobmFtZSwgcGFyYW1ldGVyczogcGFyYW1ldGVycykpOwoKICBAb3ZlcnJpZGUKICBGdXR1cmU8dm9pZD4gbG9nU2lnbkluKHtTdHJpbmc/IG1ldGhvZCwgTWFwPFN0cmluZywgT2JqZWN0Pj8gcGFyYW1ldGVyc30pID0+CiAgICAgIF9mb3JBbGwoCiAgICAgICAgKHNlcnZpY2UpID0+IHNlcnZpY2UubG9nU2lnbkluKG1ldGhvZDogbWV0aG9kLCBwYXJhbWV0ZXJzOiBwYXJhbWV0ZXJzKSwKICAgICAgKTsKCiAgQG92ZXJyaWRlCiAgRnV0dXJlPHZvaWQ+IGxvZ1NpZ25VcCh7CiAgICByZXF1aXJlZCBTdHJpbmcgbWV0aG9kLAogICAgTWFwPFN0cmluZywgT2JqZWN0Pj8gcGFyYW1ldGVycywKICB9KSA9PgogICAgICBfZm9yQWxsKAogICAgICAgIChzZXJ2aWNlKSA9PiBzZXJ2aWNlLmxvZ1NpZ25VcChtZXRob2Q6IG1ldGhvZCwgcGFyYW1ldGVyczogcGFyYW1ldGVycyksCiAgICAgICk7CgogIEBvdmVycmlkZQogIEZ1dHVyZTx2b2lkPiBzZXRBbmFseXRpY3NDb2xsZWN0aW9uRW5hYmxlZChib29sIGVuYWJsZWQpID0+CiAgICAgIF9mb3JBbGwoKHNlcnZpY2UpID0+IHNlcnZpY2Uuc2V0QW5hbHl0aWNzQ29sbGVjdGlvbkVuYWJsZWQoZW5hYmxlZCkpOwoKICBAb3ZlcnJpZGUKICBGdXR1cmU8dm9pZD4gc2V0VXNlcklkKFN0cmluZz8gdXNlcklkKSA9PgogICAgICBfZm9yQWxsKChzZXJ2aWNlKSA9PiBzZXJ2aWNlLnNldFVzZXJJZCh1c2VySWQpKTsKCiAgQG92ZXJyaWRlCiAgRnV0dXJlPHZvaWQ+IHNldFVzZXJQcm9wZXJ0eSh7CiAgICByZXF1aXJlZCBTdHJpbmcgbmFtZSwKICAgIHJlcXVpcmVkIFN0cmluZz8gdmFsdWUsCiAgfSkgPT4KICAgICAgX2ZvckFsbCgoc2VydmljZSkgPT4gc2VydmljZS5zZXRVc2VyUHJvcGVydHkobmFtZTogbmFtZSwgdmFsdWU6IHZhbHVlKSk7CgogIEZ1dHVyZTx2b2lkPiBfZm9yQWxsKAogICAgRnV0dXJlPHZvaWQ+IEZ1bmN0aW9uKEFuYWx5dGljc1NlcnZpY2Ugc2VydmljZSkgY2FsbCwKICApIGFzeW5jIHsKICAgIGF3YWl0IEZ1dHVyZS53YWl0KF9zZXJ2aWNlcy5tYXAoY2FsbCkpOwogIH0KfQo=",
      "type": "text"
    }
  ],
  "hooks": [],
  "name": "analytics_role",
  "description":
      "The template of the analytics role of SMF: the analytics service.",
  "version": "0.1.0+1",
  "environment": {"mason": "^0.1.1"},
  "vars": {}
});
