// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, implicit_dynamic_list_literal, implicit_dynamic_map_literal, inference_failure_on_collection_literal

import 'package:mason/mason.dart';

final localizationRoleSettingsBundle = MasonBundle.fromJson(<String, dynamic>{
  "files": [
    {
      "path": "lib/core/l10n/language_setting.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmZsdXR0ZXIvbWF0ZXJpYWwuZGFydCc7CgppbXBvcnQgJ2FwcF9sb2NhbGUuZGFydCc7CgovLy8gVGhlIG5hbWVzIG9mIHRoZSBsYW5ndWFnZXMgb2YgdGhlIGFwcCwgZWFjaCBpbiBpdHMgb3duIGxhbmd1YWdlLCBieSB0aGUKLy8vIGNvZGUgb2YgdGhlIGxhbmd1YWdlLiBUaGUgc2V0dGluZyBzaG93cyBhIGxhbmd1YWdlIG9mIHRoZSBhcHAgd2l0aG91dCBhCi8vLyBuYW1lIGhlcmUgYnkgaXRzIGNvZGU6IGFkZCB0aGUgbmFtZSBvZiBzdWNoIGEgbGFuZ3VhZ2UuCmNvbnN0IF9uYW1lcyA9IDxTdHJpbmcsIFN0cmluZz57Cnt7e2xvY2FsZV9uYW1lc319fQp9OwoKLy8vIFRoZSBzZXR0aW5nIG9mIHRoZSBsYW5ndWFnZSBvZiB0aGUgYXBwLCBhbiBlbnRyeSBvZiB0aGUgc2V0dGluZ3Mgc2NyZWVuOgovLy8gaXQgc2hvd3MgdGhlIGxhbmd1YWdlIHRoYXQgdGhlIHVzZXIgY2hvc2UsIGFuZCBsZXRzIHRoZSB1c2VyIGNob29zZSBvbmUKLy8vIG9mIHRoZSBsYW5ndWFnZXMgb2YgdGhlIGFwcCwgb3IgZm9sbG93IHRoZSBsYW5ndWFnZXMgb2YgdGhlIGRldmljZS4KY2xhc3MgTGFuZ3VhZ2VTZXR0aW5nIGV4dGVuZHMgU3RhdGVsZXNzV2lkZ2V0IHsKICAvLy8gQ3JlYXRlcyB0aGUgc2V0dGluZy4KICBjb25zdCBMYW5ndWFnZVNldHRpbmcoe3N1cGVyLmtleX0pOwoKICBAb3ZlcnJpZGUKICBXaWRnZXQgYnVpbGQoQnVpbGRDb250ZXh0IGNvbnRleHQpIHsKICAgIGZpbmFsIGNob3NlbiA9IEFwcExvY2FsZVNjb3BlLm9mKGNvbnRleHQpOwogICAgcmV0dXJuIExpc3RUaWxlKAogICAgICBsZWFkaW5nOiBjb25zdCBJY29uKEljb25zLmxhbmd1YWdlKSwKICAgICAgdGl0bGU6IFRleHQoe3t7dGV4dF9sYW5ndWFnZX19fSksCiAgICAgIHN1YnRpdGxlOiBUZXh0KGNob3NlbiA9PSBudWxsID8ge3t7dGV4dF9zeXN0ZW19fX0gOiBfbmFtZU9mKGNob3NlbikpLAogICAgICBvblRhcDogKCkgPT4gc2hvd0RpYWxvZzx2b2lkPigKICAgICAgICBjb250ZXh0OiBjb250ZXh0LAogICAgICAgIGJ1aWxkZXI6IChjb250ZXh0KSA9PiBjb25zdCBfTGFuZ3VhZ2VEaWFsb2coKSwKICAgICAgKSwKICAgICk7CiAgfQp9CgovLy8gVGhlIG5hbWUgb2YgdGhlIGxhbmd1YWdlIG9mIFtsb2NhbGVdIGluIHRoYXQgbGFuZ3VhZ2UsIG9yIGl0cyBjb2RlLgpTdHJpbmcgX25hbWVPZihMb2NhbGUgbG9jYWxlKSA9PgogICAgX25hbWVzW2xvY2FsZS5sYW5ndWFnZUNvZGVdID8/IGxvY2FsZS5sYW5ndWFnZUNvZGU7CgovLy8gVGhlIGNob2ljZSBiZXR3ZWVuIHRoZSBsYW5ndWFnZXMgb2YgdGhlIGFwcCBhbmQgdGhvc2Ugb2YgdGhlIGRldmljZS4KY2xhc3MgX0xhbmd1YWdlRGlhbG9nIGV4dGVuZHMgU3RhdGVsZXNzV2lkZ2V0IHsKICBjb25zdCBfTGFuZ3VhZ2VEaWFsb2coKTsKCiAgQG92ZXJyaWRlCiAgV2lkZ2V0IGJ1aWxkKEJ1aWxkQ29udGV4dCBjb250ZXh0KSB7CiAgICBmaW5hbCBjaG9zZW4gPSBBcHBMb2NhbGVTY29wZS5vZihjb250ZXh0KTsKICAgIHJldHVybiBTaW1wbGVEaWFsb2coCiAgICAgIHRpdGxlOiBUZXh0KHt7e3RleHRfbGFuZ3VhZ2V9fX0pLAogICAgICBjaGlsZHJlbjogWwogICAgICAgIGZvciAoZmluYWwgTG9jYWxlPyBsb2NhbGUgaW4gW251bGwsIC4uLmFwcExvY2FsZXNdKQogICAgICAgICAgTGlzdFRpbGUoCiAgICAgICAgICAgIHRpdGxlOiBUZXh0KGxvY2FsZSA9PSBudWxsID8ge3t7dGV4dF9zeXN0ZW19fX0gOiBfbmFtZU9mKGxvY2FsZSkpLAogICAgICAgICAgICBzZWxlY3RlZDogbG9jYWxlID09IGNob3NlbiwKICAgICAgICAgICAgdHJhaWxpbmc6IGxvY2FsZSA9PSBjaG9zZW4gPyBjb25zdCBJY29uKEljb25zLmNoZWNrKSA6IG51bGwsCiAgICAgICAgICAgIG9uVGFwOiAoKSBhc3luYyB7CiAgICAgICAgICAgICAgTmF2aWdhdG9yLm9mKGNvbnRleHQpLnBvcCgpOwogICAgICAgICAgICAgIGF3YWl0IGFwcExvY2FsZS5jaG9vc2UobG9jYWxlKTsKICAgICAgICAgICAgfSwKICAgICAgICAgICksCiAgICAgIF0sCiAgICApOwogIH0KfQo=",
      "type": "text"
    }
  ],
  "hooks": [],
  "name": "localization_role_settings",
  "description":
      "The template of the localization role of SMF for an app with a settings screen: the setting of the language of the app.",
  "version": "0.1.0+1",
  "environment": {"mason": "^0.1.1"},
  "vars": {}
});
