// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, implicit_dynamic_list_literal, implicit_dynamic_map_literal, inference_failure_on_collection_literal

import 'package:mason/mason.dart';

final localizationRoleSettingsBundle = MasonBundle.fromJson(<String, dynamic>{
  "files": [
    {
      "path": "lib/core/l10n/language_setting.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmZsdXR0ZXIvbWF0ZXJpYWwuZGFydCc7CgppbXBvcnQgJ2FwcF9sb2NhbGUuZGFydCc7CgovLy8gVGhlIG5hbWVzIG9mIHRoZSBsYW5ndWFnZXMgb2YgdGhlIGFwcCwgZWFjaCBpbiBpdHMgb3duIGxhbmd1YWdlLCBieSB0aGUKLy8vIGNvZGUgb2YgdGhlIGxhbmd1YWdlLiBUaGUgc2V0dGluZyBzaG93cyBhIGxhbmd1YWdlIG9mIHRoZSBhcHAgd2l0aG91dCBhCi8vLyBuYW1lIGhlcmUgYnkgaXRzIGNvZGU6IGFkZCB0aGUgbmFtZSBvZiBzdWNoIGEgbGFuZ3VhZ2UuCmNvbnN0IF9uYW1lcyA9IDxTdHJpbmcsIFN0cmluZz57Cnt7e2xvY2FsZV9uYW1lc319fQp9OwoKLy8vIFRoZSBzZXR0aW5nIG9mIHRoZSBsYW5ndWFnZSBvZiB0aGUgYXBwLCBhbiBlbnRyeSBvZiB0aGUgc2V0dGluZ3Mgc2NyZWVuOgovLy8gaXQgc2hvd3MgdGhlIGxhbmd1YWdlIHRoYXQgdGhlIHVzZXIgY2hvc2UsIGFuZCBsZXRzIHRoZSB1c2VyIGNob29zZSBvbmUKLy8vIG9mIHRoZSBsYW5ndWFnZXMgb2YgdGhlIGFwcCwgb3IgZm9sbG93IHRoZSBsYW5ndWFnZXMgb2YgdGhlIGRldmljZS4KLy8vCi8vLyBUaGUgZW50cnkgZG9lcyBub3Qgd2FpdCB1bnRpbCBhIGNob2ljZSBpcyBzYXZlZC4gSWYgdGhlIHByZWZlcmVuY2VzIGZhaWwKLy8vIHRvIHNhdmUgaXQsIHRoZSBhcHAgaXMgaW4gdGhlIGNob3NlbiBsYW5ndWFnZSB3aGlsZSBpdCBydW5zLCBpdHMgbmV4dAovLy8gbGF1bmNoIHN0YXJ0cyB3aXRoIHdoYXQgd2FzIHNhdmVkIGJlZm9yZSwgYW5kIHRoZSBlcnJvciBpcyBvbmUgdGhhdAovLy8gbm90aGluZyBoZXJlIGNhdGNoZXM6IGl0IHJlYWNoZXMgdGhlIGhhbmRsZXJzIG9mIHRoZSB1bmNhdWdodCBlcnJvcnMgb2YKLy8vIHRoZSBhcHAuCmNsYXNzIExhbmd1YWdlU2V0dGluZyBleHRlbmRzIFN0YXRlbGVzc1dpZGdldCB7CiAgLy8vIENyZWF0ZXMgdGhlIHNldHRpbmcuCiAgY29uc3QgTGFuZ3VhZ2VTZXR0aW5nKHtzdXBlci5rZXl9KTsKCiAgQG92ZXJyaWRlCiAgV2lkZ2V0IGJ1aWxkKEJ1aWxkQ29udGV4dCBjb250ZXh0KSB7CiAgICBmaW5hbCBjaG9zZW4gPSBBcHBMb2NhbGVTY29wZS5vZihjb250ZXh0KTsKICAgIHJldHVybiBMaXN0VGlsZSgKICAgICAgbGVhZGluZzogY29uc3QgSWNvbihJY29ucy5sYW5ndWFnZSksCiAgICAgIHRpdGxlOiBUZXh0KHt7e3RleHRfbGFuZ3VhZ2V9fX0pLAogICAgICBzdWJ0aXRsZTogVGV4dChjaG9zZW4gPT0gbnVsbCA/IHt7e3RleHRfc3lzdGVtfX19IDogX25hbWVPZihjaG9zZW4pKSwKICAgICAgb25UYXA6ICgpID0+IHNob3dEaWFsb2c8dm9pZD4oCiAgICAgICAgY29udGV4dDogY29udGV4dCwKICAgICAgICBidWlsZGVyOiAoY29udGV4dCkgPT4gY29uc3QgX0xhbmd1YWdlRGlhbG9nKCksCiAgICAgICksCiAgICApOwogIH0KfQoKLy8vIFRoZSBuYW1lIG9mIHRoZSBsYW5ndWFnZSBvZiBbbG9jYWxlXSBpbiB0aGF0IGxhbmd1YWdlLCBvciBpdHMgY29kZS4KU3RyaW5nIF9uYW1lT2YoTG9jYWxlIGxvY2FsZSkgPT4KICAgIF9uYW1lc1tsb2NhbGUubGFuZ3VhZ2VDb2RlXSA/PyBsb2NhbGUubGFuZ3VhZ2VDb2RlOwoKLy8vIFRoZSBjaG9pY2UgYmV0d2VlbiB0aGUgbGFuZ3VhZ2VzIG9mIHRoZSBhcHAgYW5kIHRob3NlIG9mIHRoZSBkZXZpY2UuCmNsYXNzIF9MYW5ndWFnZURpYWxvZyBleHRlbmRzIFN0YXRlbGVzc1dpZGdldCB7CiAgY29uc3QgX0xhbmd1YWdlRGlhbG9nKCk7CgogIEBvdmVycmlkZQogIFdpZGdldCBidWlsZChCdWlsZENvbnRleHQgY29udGV4dCkgewogICAgZmluYWwgY2hvc2VuID0gQXBwTG9jYWxlU2NvcGUub2YoY29udGV4dCk7CiAgICByZXR1cm4gU2ltcGxlRGlhbG9nKAogICAgICB0aXRsZTogVGV4dCh7e3t0ZXh0X2xhbmd1YWdlfX19KSwKICAgICAgY2hpbGRyZW46IFsKICAgICAgICBmb3IgKGZpbmFsIExvY2FsZT8gbG9jYWxlIGluIFtudWxsLCAuLi5hcHBMb2NhbGVzXSkKICAgICAgICAgIExpc3RUaWxlKAogICAgICAgICAgICB0aXRsZTogVGV4dChsb2NhbGUgPT0gbnVsbCA/IHt7e3RleHRfc3lzdGVtfX19IDogX25hbWVPZihsb2NhbGUpKSwKICAgICAgICAgICAgc2VsZWN0ZWQ6IGxvY2FsZSA9PSBjaG9zZW4sCiAgICAgICAgICAgIHRyYWlsaW5nOiBsb2NhbGUgPT0gY2hvc2VuID8gY29uc3QgSWNvbihJY29ucy5jaGVjaykgOiBudWxsLAogICAgICAgICAgICBvblRhcDogKCkgYXN5bmMgewogICAgICAgICAgICAgIE5hdmlnYXRvci5vZihjb250ZXh0KS5wb3AoKTsKICAgICAgICAgICAgICBhd2FpdCBhcHBMb2NhbGUuY2hvb3NlKGxvY2FsZSk7CiAgICAgICAgICAgIH0sCiAgICAgICAgICApLAogICAgICBdLAogICAgKTsKICB9Cn0K",
      "type": "text"
    }
  ],
  "hooks": [],
  "name": "localization_role_settings",
  "description":
      "The template of the localization role of SMF for an app with a settings screen: the setting of the language of the app.",
  "version": "0.1.0+1",
  "environment": {"mason": "^0.1.1"},
  "vars": {}
});
