// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, implicit_dynamic_list_literal, implicit_dynamic_map_literal, inference_failure_on_collection_literal

import 'package:mason/mason.dart';

final themeRoleSettingBundle = MasonBundle.fromJson(<String, dynamic>{
  "files": [
    {
      "path": "lib/core/theme/theme_mode_setting.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmZsdXR0ZXIvbWF0ZXJpYWwuZGFydCc7CgppbXBvcnQgJ3RoZW1lX21vZGUuZGFydCc7CgovLy8gVGhlIHNldHRpbmcgb2YgdGhlIHRoZW1lIG1vZGUgb2YgdGhlIGFwcCwgYW4gZW50cnkgb2YgdGhlIHNldHRpbmdzCi8vLyBzY3JlZW46IGl0IHNob3dzIHRoZSBtb2RlIHRoYXQgdGhlIHVzZXIgc2VsZWN0ZWQsIGFuZCBsZXRzIHRoZSB1c2VyCi8vLyBzZWxlY3Qgd2hldGhlciB0aGUgYXBwIGlzIGxpZ2h0LCBkYXJrLCBvciBmb2xsb3dzIHRoZSBkZXZpY2UuCi8vLwovLy8gVGhlIGVudHJ5IGRvZXMgbm90IHdhaXQgdW50aWwgYSBjaG9pY2UgaXMgc2F2ZWQuIElmIHRoZSBwcmVmZXJlbmNlcyBmYWlsCi8vLyB0byBzYXZlIGl0LCB0aGUgYXBwIHNob3dzIHRoZSBzZWxlY3RlZCBtb2RlIHdoaWxlIGl0IHJ1bnMsIGl0cyBuZXh0Ci8vLyBsYXVuY2ggaGFzIHRoZSBtb2RlIHRoYXQgd2FzIHNhdmVkIGJlZm9yZSwgYW5kIHRoZSBlcnJvciBpcyBvbmUgdGhhdAovLy8gbm90aGluZyBoZXJlIGNhdGNoZXM6IGl0IHJlYWNoZXMgdGhlIGhhbmRsZXJzIG9mIHRoZSB1bmNhdWdodCBlcnJvcnMgb2YKLy8vIHRoZSBhcHAuCmNsYXNzIFRoZW1lTW9kZVNldHRpbmcgZXh0ZW5kcyBTdGF0ZWxlc3NXaWRnZXQgewogIC8vLyBDcmVhdGVzIHRoZSBzZXR0aW5nLgogIGNvbnN0IFRoZW1lTW9kZVNldHRpbmcoe3N1cGVyLmtleX0pOwoKICBAb3ZlcnJpZGUKICBXaWRnZXQgYnVpbGQoQnVpbGRDb250ZXh0IGNvbnRleHQpID0+IFJhZGlvR3JvdXA8VGhlbWVNb2RlPigKICAgICAgICBncm91cFZhbHVlOiBBcHBUaGVtZU1vZGVTY29wZS5vZihjb250ZXh0KSwKICAgICAgICBvbkNoYW5nZWQ6IChtb2RlKSB7CiAgICAgICAgICBpZiAobW9kZSAhPSBudWxsKSBhcHBUaGVtZU1vZGUuY2hvb3NlKG1vZGUpOwogICAgICAgIH0sCiAgICAgICAgY2hpbGQ6IENvbHVtbigKICAgICAgICAgIG1haW5BeGlzU2l6ZTogTWFpbkF4aXNTaXplLm1pbiwKICAgICAgICAgIGNyb3NzQXhpc0FsaWdubWVudDogQ3Jvc3NBeGlzQWxpZ25tZW50LnN0cmV0Y2gsCiAgICAgICAgICBjaGlsZHJlbjogWwogICAgICAgICAgICBMaXN0VGlsZSgKICAgICAgICAgICAgICBsZWFkaW5nOiBjb25zdCBJY29uKEljb25zLmJyaWdodG5lc3NfNl9vdXRsaW5lZCksCiAgICAgICAgICAgICAgdGl0bGU6IFRleHQoe3t7dGV4dF90aXRsZX19fSksCiAgICAgICAgICAgICksCiAgICAgICAgICAgIFJhZGlvTGlzdFRpbGU8VGhlbWVNb2RlPigKICAgICAgICAgICAgICB2YWx1ZTogVGhlbWVNb2RlLnN5c3RlbSwKICAgICAgICAgICAgICB0aXRsZTogVGV4dCh7e3t0ZXh0X3N5c3RlbX19fSksCiAgICAgICAgICAgICksCiAgICAgICAgICAgIFJhZGlvTGlzdFRpbGU8VGhlbWVNb2RlPigKICAgICAgICAgICAgICB2YWx1ZTogVGhlbWVNb2RlLmxpZ2h0LAogICAgICAgICAgICAgIHRpdGxlOiBUZXh0KHt7e3RleHRfbGlnaHR9fX0pLAogICAgICAgICAgICApLAogICAgICAgICAgICBSYWRpb0xpc3RUaWxlPFRoZW1lTW9kZT4oCiAgICAgICAgICAgICAgdmFsdWU6IFRoZW1lTW9kZS5kYXJrLAogICAgICAgICAgICAgIHRpdGxlOiBUZXh0KHt7e3RleHRfZGFya319fSksCiAgICAgICAgICAgICksCiAgICAgICAgICBdLAogICAgICAgICksCiAgICAgICk7Cn0K",
      "type": "text"
    }
  ],
  "hooks": [],
  "name": "theme_role_setting",
  "description":
      "The template of the theme role of SMF for an app with a settings screen: the entry in which the user selects the theme mode.",
  "version": "0.1.0+1",
  "environment": {"mason": "^0.1.1"},
  "vars": {}
});
