version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/packages/smf_flutter_cli"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      dart-deps:
        patterns:
          - "*"

  - package-ecosystem: "pub"
    directory: "/packages/smf_flutter_cli/bricks/smf_cli_brick/hooks"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      dart-deps:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      gh-deps:
        patterns:
          - "*"
