version: 2
updates:
  - package-ecosystem: "pub"
    directories:
      - "/packages/smf_flutter_cli"
      - "/packages/smf_contracts"
      - "/packages/smf_pipeline"
      - "/packages/smf_modules/*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      dart-deps:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      gh-deps:
        patterns:
          - "*"
