name: smf_flutter_cli_monorepo
description: A monorepo containing SMF Flutter CLI tools and modules for scaffolding Flutter applications
version: 0.1.0
homepage: https://saymyframe.com
repository: https://github.com/saymyframe/smf_flutter_cli
issue_tracker: https://github.com/saymyframe/smf_flutter_cli/issues
license: Apache-2.0
authors:
  - SayMyFrame Team <team@saymyframe.com>
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  smfflutter: smfflutter_dev

dev_dependencies:
  smf_flutter_cli:
    path: packages/smf_flutter_cli
  melos: ^6.3.3

dependency_overrides:
  smf_flutter_cli:
    path: packages/smf_flutter_cli
