name: smf_flutter_cli_monorepo
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  smfflutter: smfflutter_dev

dev_dependencies:
  smf_flutter_cli:
    path: packages/smf_flutter_cli
  melos: ^6.3.3

dependency_overrides:
  smf_flutter_cli:
    path: packages/smf_flutter_cli
