name: smf_flutter_cli_monorepo
description: A monorepo containing SMF Flutter CLI tools and modules for scaffolding Flutter applications
version: 0.1.0
homepage: https://saymyframe.com
repository: https://github.com/saymyframe/smf_flutter_cli
issue_tracker: https://github.com/saymyframe/smf_flutter_cli/issues
license: Apache-2.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  smfflutter: smfflutter_dev

dev_dependencies:
  lints: ^3.0.0
  smf_flutter_cli:
    path: packages/smf_flutter_cli
  melos: ^7.1.0

dependency_overrides:
  smf_flutter_cli:
    path: packages/smf_flutter_cli
