sonar.projectKey=saymyframe_smf_flutter_cli
sonar.organization=saymyframe
sonar.sources=packages
sonar.exclusions=**/bricks/**,**/__brick__/**,**/bundles/**,**/test/**,**/*.g.dart,**/*.freezed.dart

sonar.tests=packages
sonar.test.inclusions=**/test/**/*_test.dart
sonar.dart.lcov.reportPaths=packages/smf_flutter_cli/coverage/lcov.info
