sonar.projectKey=saymyframe_smf_flutter_cli
sonar.organization=saymyframe
sonar.sources=packages
sonar.exclusions=**/bricks/**,**/__brick__/**,**/bundles/**,**/test/**,**/fixture_registry/**,**/*.g.dart,**/*.freezed.dart

sonar.tests=packages
sonar.test.inclusions=**/test/**/*_test.dart

# Written by `melos run test:coverage`; packages without tests are skipped.
sonar.dart.lcov.reportPaths=\
  packages/smf_contracts/coverage/lcov.info,\
  packages/smf_pipeline/coverage/lcov.info,\
  packages/smf_flutter_cli/coverage/lcov.info,\
  packages/smf_modules/smf_contribution_engine/coverage/lcov.info,\
  packages/smf_modules/smf_event_bus/coverage/lcov.info,\
  packages/smf_modules/smf_firebase_analytics/coverage/lcov.info,\
  packages/smf_modules/smf_firebase_core/coverage/lcov.info,\
  packages/smf_modules/smf_firebase_crashlytics/coverage/lcov.info,\
  packages/smf_modules/smf_flutter_core/coverage/lcov.info,\
  packages/smf_modules/smf_get_it/coverage/lcov.info,\
  packages/smf_modules/smf_go_router/coverage/lcov.info,\
  packages/smf_modules/smf_home_flutter/coverage/lcov.info
