// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, implicit_dynamic_list_literal, implicit_dynamic_map_literal, inference_failure_on_collection_literal

import 'package:mason/mason.dart';

final bottomTabsBundle = MasonBundle.fromJson(<String, dynamic>{
  "files": [
    {
      "path": "lib/core/layout/app_shell.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmZsdXR0ZXIvbWF0ZXJpYWwuZGFydCc7CgppbXBvcnQgJ2Rlc3RpbmF0aW9uLmRhcnQnOwoKLy8vIFRoZSBtYWluIG5hdmlnYXRpb24gb2YgdGhlIGFwcDogYSBiYXIgYXQgdGhlIGJvdHRvbSB3aXRoIGEgdGFiIGZvciBlYWNoCi8vLyBkZXN0aW5hdGlvbiwgYmVsb3cgdGhlIHNjcmVlbiBvZiB0aGUgc2VsZWN0ZWQgb25lLgovLy8KLy8vIFdpdGggb25lIGRlc3RpbmF0aW9uIHRoZXJlIGlzIG5vdGhpbmcgdG8gc3dpdGNoIHRvLCBzbyB0aGUgYmFyIGlzCi8vLyBoaWRkZW4gYW5kIHRoZSBzY3JlZW4gZmlsbHMgdGhlIGFwcC4KY2xhc3MgQXBwU2hlbGwgZXh0ZW5kcyBTdGF0ZWxlc3NXaWRnZXQgewogIC8vLyBDcmVhdGVzIHRoZSBtYWluIG5hdmlnYXRpb24gd2l0aCBbZGVzdGluYXRpb25zXSwgdGhlIG9uZSBhdAogIC8vLyBbY3VycmVudEluZGV4XSBzZWxlY3RlZCB3aXRoIFtib2R5XSBhcyBpdHMgc2NyZWVuOyBzZWxlY3RpbmcgYSB0YWIKICAvLy8gY2FsbHMgW29uU2VsZWN0XSB3aXRoIGl0cyBpbmRleC4KICBjb25zdCBBcHBTaGVsbCh7CiAgICByZXF1aXJlZCB0aGlzLmRlc3RpbmF0aW9ucywKICAgIHJlcXVpcmVkIHRoaXMuY3VycmVudEluZGV4LAogICAgcmVxdWlyZWQgdGhpcy5vblNlbGVjdCwKICAgIHJlcXVpcmVkIHRoaXMuYm9keSwKICAgIHN1cGVyLmtleSwKICB9KTsKCiAgLy8vIFRoZSB0YWJzIG9mIHRoZSBiYXIsIGluIG9yZGVyLgogIGZpbmFsIExpc3Q8RGVzdGluYXRpb24+IGRlc3RpbmF0aW9uczsKCiAgLy8vIFRoZSBpbmRleCBvZiB0aGUgc2VsZWN0ZWQgZGVzdGluYXRpb24uCiAgZmluYWwgaW50IGN1cnJlbnRJbmRleDsKCiAgLy8vIFNlbGVjdHMgdGhlIGRlc3RpbmF0aW9uIGF0IHRoZSBnaXZlbiBpbmRleC4KICBmaW5hbCBWYWx1ZUNoYW5nZWQ8aW50PiBvblNlbGVjdDsKCiAgLy8vIFRoZSBzY3JlZW4gb2YgdGhlIHNlbGVjdGVkIGRlc3RpbmF0aW9uLgogIGZpbmFsIFdpZGdldCBib2R5OwoKICBAb3ZlcnJpZGUKICBXaWRnZXQgYnVpbGQoQnVpbGRDb250ZXh0IGNvbnRleHQpID0+IFNjYWZmb2xkKAogICAgYm9keTogYm9keSwKICAgIGJvdHRvbU5hdmlnYXRpb25CYXI6IGRlc3RpbmF0aW9ucy5sZW5ndGggPCAyCiAgICAgICAgPyBudWxsCiAgICAgICAgOiBOYXZpZ2F0aW9uQmFyKAogICAgICAgICAgICBzZWxlY3RlZEluZGV4OiBjdXJyZW50SW5kZXgsCiAgICAgICAgICAgIG9uRGVzdGluYXRpb25TZWxlY3RlZDogb25TZWxlY3QsCiAgICAgICAgICAgIGRlc3RpbmF0aW9uczogWwogICAgICAgICAgICAgIGZvciAoZmluYWwgZGVzdGluYXRpb24gaW4gZGVzdGluYXRpb25zKQogICAgICAgICAgICAgICAgTmF2aWdhdGlvbkRlc3RpbmF0aW9uKAogICAgICAgICAgICAgICAgICBpY29uOiBJY29uKGRlc3RpbmF0aW9uLmljb24pLAogICAgICAgICAgICAgICAgICBsYWJlbDogZGVzdGluYXRpb24ubGFiZWwsCiAgICAgICAgICAgICAgICApLAogICAgICAgICAgICBdLAogICAgICAgICAgKSwKICApOwp9Cg==",
      "type": "text"
    }
  ],
  "hooks": [],
  "name": "bottom_tabs",
  "description":
      "The main navigation of an SMF app: a bar of tabs at the bottom, one for each destination.",
  "version": "0.1.0+1",
  "environment": {"mason": "^0.1.1"},
  "vars": {}
});
