import 'dart:convert';

import 'package:mason/mason.dart' show MasonBundledFile, RenderTemplate;
import 'package:smf_contracts/core.dart';
import 'package:smf_pipeline/src/access.dart';
import 'package:smf_pipeline/src/collector.dart';
import 'package:smf_pipeline/src/errors.dart';
import 'package:smf_pipeline/src/imports.dart';
import 'package:smf_pipeline/src/machine_files.dart';
import 'package:smf_pipeline/src/order.dart';
import 'package:smf_pipeline/src/pubspec.dart';
import 'package:smf_pipeline/src/registry.dart';
import 'package:smf_pipeline/src/resolver.dart';
import 'package:smf_pipeline/src/templates.dart';
import 'package:smf_pipeline/src/validation.dart';

/// An import that the pipeline added to a file of the app for a fragment,
/// with who contributed the fragment.
final class AddedImport {
  /// Creates the record of [import], needed by [contributor].
  const AddedImport(this.import, this.contributor);

  /// The import, as the fragment gave it.
  final ImportRef import;

  /// Who contributed the fragment that needs it.
  final ContributionOrigin contributor;
}

/// A file of the app that stage 8 rendered.
final class RenderedFile {
  /// Creates the file at [path] with [bytes], generated by [owner].
  const RenderedFile({
    required this.path,
    required this.bytes,
    required this.owner,
    this.isText = true,
    this.addedImports = const [],
  });

  /// The path relative to the root of the app, with forward slashes.
  final String path;

  /// The content.
  final List<int> bytes;

  /// Whether the file is text, which mason renders, or binary, which it
  /// copies.
  final bool isText;

  /// Who generated the file: the owner of its brick.
  final ContributionOrigin owner;

  /// The imports the pipeline added to the file for the fragments of the
  /// sockets whose tags it holds and of the fragment variables it reads,
  /// one for each fragment that needs it, resolved in the app: an import
  /// the file already had is not among them.
  final List<AddedImport> addedImports;

  /// The content as text.
  String get text => utf8.decode(bytes, allowMalformed: true);

  RenderedFile _withText(String text, List<AddedImport> addedImports) =>
      RenderedFile(
        path: path,
        bytes: utf8.encode(text),
        owner: owner,
        isText: isText,
        addedImports: addedImports,
      );
}

/// The app that stage 8 rendered, in memory.
final class RenderedApp {
  /// Creates the app of [files].
  RenderedApp(Iterable<RenderedFile> files)
      : files = Map.unmodifiable({
          for (final file
              in files.toList()..sort((a, b) => a.path.compareTo(b.path)))
            file.path: file,
        });

  /// The files by path, relative to the root of the app, sorted by path.
  final Map<String, RenderedFile> files;

  /// The text of every text file, by path.
  Map<String, String> get texts => {
        for (final file in files.values)
          if (file.isText) file.path: file.text,
      };

  /// Who generated each file, by path.
  Map<String, ContributionOrigin> get owners => {
        for (final file in files.values) file.path: file.owner,
      };
}

/// What the render hooks of the roles and their providers returned.
final class _HookOutput {
  /// The fragments that apply, each with its origin.
  final List<Collected> fragments = [];

  /// The brick variables of each owner: a module or a role template. A
  /// variable that is a [Fragment] is its code here.
  final Map<ContributionOrigin, Map<String, Object?>> vars = {};

  /// The brick variables of each owner that are fragments of code, by name.
  final Map<ContributionOrigin, Map<String, Fragment>> fragmentVars = {};
}

/// The imports of the fragment variables that the templates of the bricks
/// read, by owner and path of the template file.
final class _VariableImports {
  /// The imports for each template file.
  final Map<(ContributionOrigin, String), List<AddedImport>> imports = {};

  /// The fragment variables with imports that each template file reads.
  final Map<(ContributionOrigin, String), Set<String>> names = {};

  /// The fragment variables that a template of their owner reads, by owner
  /// and name.
  final Set<(ContributionOrigin, String)> read = {};
}

/// Stage 8 of the pipeline: renders the app in memory.
///
/// 1. Runs the render hooks of the templates and providers of the present
///    roles, with the results of [choices]. Their fragments follow the rules
///    of the contributions of their owner, and their brick variables must
///    not be reserved (see [isReservedVar]) or set twice for one owner. A
///    variable may be a [Fragment] of code, see [RoleOutput.vars].
/// 2. Orders the contributions of every socket, those of the render hooks
///    included (see [orderContributions]), and renders each socket into the
///    text of its tags. A socket that gets contributions but has no tag in
///    any brick is an error, since its code would be lost. The sockets of
///    the pipeline get the sections of the merged [pubspec], and the tags
///    of sockets that get nothing render to nothing: a line that holds
///    nothing but such a tag goes away with it.
/// 3. Renders every brick that applies with mason, with the variables of
///    [BrickContribution]: the names of the app, the presence flags of the
///    roles its owner provides, requires or uses, the tags, the variables of
///    its owner's render hooks and its own. A template that mason cannot
///    render, a path that leaves the app, and a path that two bricks
///    generate are errors. A fragment variable renders as its code, and a
///    line that holds nothing but one with no code goes away with it. It
///    must be read as it is, in three braces and outside mustache sections,
///    and a template that is not Dart cannot read one with imports; a
///    fragment variable that no template of its owner reads is an error,
///    since its code would be lost, unless a brick of the owner that the
///    app leaves out reads it.
/// 4. Adds the imports of each socket's fragments to the Dart file that
///    holds its tag, and those of each fragment variable to every Dart file
///    of its owner that reads it; see [addImports].
///
/// Throws a [GenerationFailedException] with every problem found.
RenderedApp renderApp({
  required ModuleRegistry registry,
  required Resolution resolution,
  required Collection collection,
  required ModuleContext context,
  required Map<Role, Object?> choices,
  required MergedPubspec pubspec,
}) {
  final issues = <SmfIssue>[];
  final hooks = _runRenderHooks(
    registry: registry,
    resolution: resolution,
    collection: collection,
    context: context,
    choices: choices,
    issues: issues,
  );
  _stopOnErrors(issues);

  final tags = scanBricks(
    registry: registry,
    resolution: resolution,
    collection: collection,
  );
  final texts = _renderSockets(
    contributions: [
      ...collection.applyingOf<SocketContribution>(),
      ...hooks.fragments,
    ],
    resolution: resolution,
    tags: tags,
    issues: issues,
  );
  texts.texts.addAll(pubspecSocketTexts(pubspec));
  _renderEmptySockets(texts.texts, tags, issues);
  _stopOnErrors(issues);

  final bricks = _BrickRenderer(
    registry: registry,
    resolution: resolution,
    context: context,
    texts: texts.texts,
    hooks: hooks,
    issues: issues,
  );
  collection.applyingOf<BrickContribution>().forEach(bricks.render);
  issues.addAll(_unreadVariableIssues(hooks, bricks.variables, collection));
  _stopOnErrors(issues);

  final files = bricks.files;
  final variables = bricks.variables;
  for (final template in {...texts.imports.keys, ...variables.imports.keys}) {
    final (owner, templatePath) = template;
    // Only text files hold tags and read variables, and every brick
    // rendered.
    final path = bricks.renderedPaths[template] ??
        (throw StateError('$templatePath of $owner was not rendered.'));
    try {
      files[path] = _withImports(
        files[path]!,
        [...?texts.imports[template], ...?variables.imports[template]],
        context.appName,
      );
    } on ImportTargetException catch (error) {
      issues.addAll(
        _importTargetIssues(template, path, error.reason, texts, variables),
      );
    }
  }
  _stopOnErrors(issues);
  return RenderedApp(files.values);
}

/// Throws a [GenerationFailedException] with the errors among [issues], if
/// there are any.
void _stopOnErrors(List<SmfIssue> issues) {
  final errors = [
    for (final issue in issues)
      if (issue.isError) issue,
  ];
  if (errors.isEmpty) return;
  throw GenerationFailedException(
    errors.length == 1
        ? 'The app cannot be rendered because of an error.'
        : 'The app cannot be rendered because of ${errors.length} errors.',
    issues: errors,
  );
}

/// Renders the tags of the sockets among [tags] that get nothing into
/// [texts] as nothing, or reports a socket that needs a value.
void _renderEmptySockets(
  Map<String, String> texts,
  BrickTags tags,
  List<SmfIssue> issues,
) {
  for (final MapEntry(key: socket, value: byName) in tags.found.entries) {
    for (final name in byName.keys) {
      if (texts.containsKey(name)) continue;
      if (socket.kind case ValueSocket(required: true)) {
        issues.add(
          SmfIssue(
            'The $socket needs a value, but nothing contributes one.',
            origin: byName[name]!.first.$2,
          ),
        );
        continue;
      }
      // A socket that gets nothing renders to nothing.
      texts[name] = '';
    }
  }
}

/// The issues of the fragment variables that the render hooks set but no
/// template of their owner reads, as [variables] recorded, so that their
/// code would be lost.
List<SmfIssue> _unreadVariableIssues(
  _HookOutput hooks,
  _VariableImports variables,
  Collection collection,
) {
  final issues = <SmfIssue>[];
  for (final MapEntry(key: owner, value: fragments)
      in hooks.fragmentVars.entries) {
    final unread = [
      for (final name in fragments.keys)
        if (!variables.read.contains((owner, name))) name,
    ];
    if (unread.isEmpty) continue;
    // A brick of the owner that this app leaves out, such as one for when a
    // role is present, may read the variable: its code is left out with it.
    final readByAny = _namesReadBy(collection, owner);
    for (final name in unread) {
      if (readByAny.contains(name)) continue;
      issues.add(
        SmfIssue(
          'The render hook of $owner sets the fragment variable $name, which '
          'no template of $owner reads, so its code would be lost.',
          origin: owner,
        ),
      );
    }
  }
  return issues;
}

/// The issues of the imports that cannot go into [path], the file of
/// [template], for the [reason]: those of the sockets whose tags it holds
/// and those of the fragment variables it reads.
List<SmfIssue> _importTargetIssues(
  (ContributionOrigin, String) template,
  String path,
  String reason,
  _SocketTexts texts,
  _VariableImports variables,
) {
  final (owner, _) = template;
  final issues = <SmfIssue>[];
  if (texts.socketsByTemplate[template] case final sockets?) {
    issues.add(
      SmfIssue(
        'The imports of the ${sockets.join(', ')} cannot go into $path, '
        'which holds ${sockets.length == 1 ? 'its tag' : 'their tags'}: '
        '$reason.',
        hint: 'Put the tag into the library file.',
        origin: owner,
        path: path,
      ),
    );
  }
  if (variables.names[template] case final names?) {
    issues.add(
      SmfIssue(
        'The imports of the fragment '
        '${names.length == 1 ? 'variable' : 'variables'} '
        '${names.join(', ')} of ${ownerOf(owner)} cannot go into $path, '
        'which reads '
        '${names.length == 1 ? 'it' : 'them'}: $reason.',
        hint: 'Read the variable in the library file.',
        origin: owner,
        path: path,
      ),
    );
  }
  return issues;
}

/// [file] with the imports of [added] that it does not have yet, and with
/// them recorded, resolved in the app of [appName].
///
/// Throws an [ImportTargetException] if the file cannot have imports.
RenderedFile _withImports(
  RenderedFile file,
  List<AddedImport> added,
  String appName,
) {
  final result = addImports(
    file.text,
    path: file.path,
    imports: [for (final import in added) import.import],
    appName: appName,
  );
  String keyOf(ImportRef import) =>
      '${import.resolveUri(appName)} as ${import.prefix}';
  final inserted = {for (final import in result.added) keyOf(import)};
  return file._withText(result.text, [
    for (final import in added)
      if (inserted.contains(keyOf(import.import)))
        AddedImport(
          ImportRef(
            import.import.resolveUri(appName),
            prefix: import.import.prefix,
            show: import.import.show,
          ),
          import.contributor,
        ),
  ]);
}

/// Runs the render hooks of the templates and providers of the present
/// roles and checks what they return.
_HookOutput _runRenderHooks({
  required ModuleRegistry registry,
  required Resolution resolution,
  required Collection collection,
  required ModuleContext context,
  required Map<Role, Object?> choices,
  required List<SmfIssue> issues,
}) {
  final request = hookRequest(
    registry: registry,
    resolution: resolution,
    collection: collection,
    context: context,
    choices: choices,
  );
  final hooks = _RenderHooks(registry, resolution, issues);
  for (final role in resolution.presentRoles) {
    // The input's runtime type argument is the role's data type, which the
    // hooks of the role's template and providers take.
    final input = role.hookInput(request);
    if (role.template case final template?) {
      hooks.add(RoleTemplateOrigin(role), () => template.render(input));
    }
    for (final module in resolution.providersOf(role)) {
      final provider = Resolution.providerObject(module, role);
      hooks.add(module.origin, () => provider.render(input));
    }
  }
  return hooks.output;
}

/// Runs render hooks, and records what they return in [output] and what is
/// wrong with it in [issues].
final class _RenderHooks {
  _RenderHooks(this.registry, this.resolution, this.issues);

  final ModuleRegistry registry;
  final Resolution resolution;
  final List<SmfIssue> issues;
  final _HookOutput output = _HookOutput();

  /// Runs [render], the render hook of [origin], and records its variables
  /// and fragments.
  void add(ContributionOrigin origin, RoleOutput Function() render) {
    final RoleOutput result;
    try {
      result = render();
    } on Object catch (error) {
      issues.add(
        SmfIssue('The render hook of $origin failed: $error', origin: origin),
      );
      return;
    }
    _addVars(origin, result);
    _addFragments(origin, result);
  }

  void _addVars(ContributionOrigin origin, RoleOutput result) {
    final vars = output.vars.putIfAbsent(origin, () => {});
    final fragments = output.fragmentVars.putIfAbsent(origin, () => {});
    // A fragment variable renders as its code, which must be text that
    // mason keeps as it is, like the value of any other variable.
    final values = {
      for (final MapEntry(:key, :value) in result.vars.entries)
        key: value is Fragment ? value.code : value,
    };
    for (final MapEntry(:key, :value) in values.entries) {
      if (isReservedVar(key)) {
        issues.add(
          SmfIssue(
            'The render hook of $origin sets the brick variable $key, which '
            'the pipeline sets itself.',
            origin: origin,
          ),
        );
      } else if (vars.containsKey(key)) {
        issues.add(
          SmfIssue(
            'Two render hooks of $origin set the brick variable $key.',
            origin: origin,
          ),
        );
      } else {
        vars[key] = value;
        if (result.vars[key] case final Fragment fragment) {
          fragments[key] = fragment;
          issues.addAll(_fragmentVarIssues(fragment, key, origin));
        }
      }
    }
    issues.addAll(_varValueIssues(values, origin));
  }

  void _addFragments(ContributionOrigin origin, RoleOutput result) {
    final present = resolution.presentRoles;
    for (final fragment in result.fragments) {
      final socket = fragment.socket;
      final collected = Collected(
        fragment.withOrigin(origin),
        origin,
        applies: fragment.when.every(present.contains) &&
            (socket.role == null || present.contains(socket.role)),
      );
      issues.addAll(contributionIssues(collected, registry, resolution));
      if (collected.applies) output.fragments.add(collected);
    }
  }
}

/// The issues of [fragment], the value of the brick variable [name] of the
/// render hook of [origin]; see [_fragmentVarProblems].
List<SmfIssue> _fragmentVarIssues(
  Fragment fragment,
  String name,
  ContributionOrigin origin,
) =>
    [
      for (final problem in _fragmentVarProblems(fragment))
        SmfIssue(
          'The fragment variable $name of the render hook of $origin '
          '$problem',
          origin: origin,
        ),
    ];

/// The issues of the brick variables [values] of the render hook of
/// [origin] that mason would change or cannot take.
List<SmfIssue> _varValueIssues(
  Map<String, Object?> values,
  ContributionOrigin origin,
) =>
    [
      for (final name in strippedVars(values))
        SmfIssue(
          'The brick variable $name of the render hook of $origin has a '
          'backslash before a line break or a non-ASCII character, which '
          'mason removes.',
          origin: origin,
        ),
      for (final name in nonPlainVars(values))
        SmfIssue(
          'The brick variable $name of the render hook of $origin is not '
          'plain data: strings, numbers, booleans, and lists and maps of '
          'them, or a fragment of code.',
          origin: origin,
        ),
    ];

/// What is wrong with [fragment], the value of a brick variable, besides
/// what [strippedVars] finds in its code: a wrapper, and imports that are
/// not valid.
List<String> _fragmentVarProblems(Fragment fragment) => [
      if (fragment.isWrapper)
        'is a Fragment.wrap, but a variable takes a Fragment of code.',
      for (final import in fragment.imports)
        for (final problem in import.problems())
          'has an invalid import. $problem',
    ];

/// The rendered sockets of an app: the text of every tag, and the imports
/// for each template file that holds a tag of a socket with imports.
final class _SocketTexts {
  /// The text of each tag.
  final Map<String, String> texts = {};

  /// The imports for each template file, by owner and template path.
  final Map<(ContributionOrigin, String), List<AddedImport>> imports = {};

  /// The sockets whose tags each of those template files holds.
  final Map<(ContributionOrigin, String), List<SocketRef>> socketsByTemplate =
      {};

  /// Records the imports of the fragments of [order], the contributions to
  /// [socket], for the template file that holds its tag at [place].
  void addImports(
    SocketRef socket,
    TagPlace place,
    ContributionOrder order,
  ) {
    final (tag, owner) = place;
    final key = (owner, tag.path);
    socketsByTemplate.putIfAbsent(key, () => []).add(socket);
    final added = imports.putIfAbsent(key, () => []);
    for (final collected in order.contributions) {
      final fragment = (collected.contribution as SocketContribution).fragment;
      for (final import in fragment?.imports ?? const <ImportRef>[]) {
        added.add(AddedImport(import, collected.origin));
      }
    }
  }
}

/// Orders [contributions] by socket and renders each socket.
_SocketTexts _renderSockets({
  required List<Collected> contributions,
  required Resolution resolution,
  required BrickTags tags,
  required List<SmfIssue> issues,
}) {
  final result = _SocketTexts();
  final bySocket = <SocketRef, List<Collected>>{};
  for (final collected in contributions) {
    final socket = (collected.contribution as SocketContribution).socket;
    bySocket.putIfAbsent(socket, () => []).add(collected);
  }

  for (final MapEntry(key: socket, value: collected) in bySocket.entries) {
    final order = orderContributions(collected, resolution);
    if (order.cycle.isNotEmpty) {
      issues.add(
        SmfIssue(
          'The contributors to the $socket cannot be ordered, because their '
          'order edges form a cycle: ${order.cycle.join(', ')}.',
          hint: 'Run with --explain to see the edges.',
        ),
      );
      continue;
    }
    final place = tags.placeOf(socket);
    if (place == null) {
      issues.add(_lostContributionsIssue(socket, order));
      continue;
    }
    final rendered = _renderSocket(socket, order, issues);
    if (rendered == null) continue;
    result.texts.addAll(rendered);
    if (socket.kind.carriesImports) result.addImports(socket, place, order);
  }
  return result;
}

/// The issue of the contributions of [order] to [socket], whose tag no
/// template of the app has, so that they would be lost.
SmfIssue _lostContributionsIssue(SocketRef socket, ContributionOrder order) {
  final contributors = {
    for (final collected in order.contributions) collected.origin,
  };
  return SmfIssue(
    '${contributors.join(', ')} '
    '${contributors.length == 1 ? 'contributes' : 'contribute'} to '
    'the $socket, but no template of the app has its tag '
    '${socket.tags.join(', ')}, so what they contribute would be lost.',
    origin: contributors.first,
  );
}

/// The text of the tags of [socket] with the contributions of [order], or
/// `null` after reporting to [issues] why it cannot be rendered.
Map<String, String>? _renderSocket(
  SocketRef socket,
  ContributionOrder order,
  List<SmfIssue> issues,
) {
  try {
    return socket.render([
      for (final collected in order.contributions)
        collected.contribution as SocketContribution,
    ]);
  } on MergeConflict catch (conflict) {
    issues.add(
      SmfIssue(
        'The contributions to the $socket conflict: $conflict.',
        origin: conflict.incomingOrigin,
      ),
    );
  } on Object catch (error) {
    issues.add(SmfIssue('The $socket cannot be rendered: $error.'));
  }
  return null;
}

/// A brick that [_BrickRenderer] renders: who contributed it, its owner,
/// its variables, and the fragment variables and module kind of its owner.
final class _Brick {
  _Brick({
    required this.origin,
    required this.name,
    required this.vars,
    required this.fragments,
    required this.kind,
  }) : owner = ownerOf(origin);

  final ContributionOrigin origin;

  /// The module or role template the brick belongs to: a variant's bricks
  /// belong to its module and get the module's variables.
  final ContributionOrigin owner;

  final String name;
  final Map<String, Object?> vars;
  final Map<String, Fragment> fragments;

  /// The kind of the module of the brick, if it has one.
  final ModuleKind? kind;
}

/// Renders the bricks of an app into [files], with the text of every tag
/// and the variables of the render hooks, and reports the problems to
/// [issues].
final class _BrickRenderer {
  _BrickRenderer({
    required this.registry,
    required this.resolution,
    required this.context,
    required this.texts,
    required this.hooks,
    required this.issues,
  });

  final ModuleRegistry registry;
  final Resolution resolution;
  final ModuleContext context;

  /// The text of every tag.
  final Map<String, String> texts;

  final _HookOutput hooks;
  final List<SmfIssue> issues;

  /// The files rendered so far, by path.
  final Map<String, RenderedFile> files = {};

  /// The path each template file rendered to, by owner and template path.
  final Map<(ContributionOrigin, String), String> renderedPaths = {};

  /// The fragment variables that the templates read, and their imports.
  final _VariableImports variables = _VariableImports();

  /// Renders the files of the brick of [collected] into [files].
  void render(Collected collected) {
    final brick = _brickOf(collected);
    final bundleFiles =
        (collected.contribution as BrickContribution).bundle.files;
    for (final file in bundleFiles) {
      _renderFile(brick, file);
    }
  }

  _Brick _brickOf(Collected collected) {
    final origin = collected.origin;
    final brick = collected.contribution as BrickContribution;
    final name = brick.bundle.name;
    // A variant's bricks belong to its module and get the module's
    // variables.
    final owner = ownerOf(origin);
    final fromHooks = hooks.vars[owner] ?? const <String, Object?>{};
    final present = resolution.presentRoles;
    final vars = <String, Object?>{
      'app_name': context.appName,
      'org_name': context.orgName,
      for (final role in rolesOf(origin, registry, resolution).access)
        role.presenceFlag: present.contains(role),
      ...texts,
      ...fromHooks,
    };
    for (final MapEntry(:key, :value) in brick.vars.entries) {
      if (fromHooks.containsKey(key)) {
        issues.add(
          SmfIssue(
            'The brick $name of $origin sets the variable $key, which a '
            'render hook of $owner sets too.',
            origin: origin,
          ),
        );
      }
      vars[key] = value;
    }
    return _Brick(
      origin: origin,
      name: name,
      vars: vars,
      fragments: hooks.fragmentVars[owner] ?? const <String, Fragment>{},
      kind: switch (origin) {
        ModuleOrigin(:final module) =>
          resolution.module(module)?.descriptor.kind,
        _ => null,
      },
    );
  }

  void _renderFile(_Brick brick, MasonBundledFile file) {
    final template = file.path.replaceAll(r'\', '/');
    final path = _pathOf(brick, template);
    if (path == null) return;
    final content = _contentOf(brick, file, template);
    if (content == null || _isGeneratedTwice(brick.origin, path)) return;
    files[path] = RenderedFile(
      path: path,
      bytes: content.bytes,
      owner: brick.origin,
      isText: content.isText,
    );
    renderedPaths[(brick.origin, template)] = path;
  }

  /// The path that [template], the path of a file of [brick], renders to,
  /// or `null` after reporting why it cannot be a path of the app.
  String? _pathOf(_Brick brick, String template) {
    final _Brick(:origin, :name, :owner) = brick;
    final pathProblems = _pathVariableProblems(
      template,
      owner: owner,
      vars: brick.vars,
      fragments: brick.fragments,
      read: (variable) => variables.read.add((owner, variable)),
    );
    for (final problem in pathProblems) {
      issues.add(
        SmfIssue(
          'The path $template in the brick $name of $origin $problem',
          hint: 'Set every variable a path reads, to "" when there is '
              'nothing.',
          origin: origin,
          path: template,
        ),
      );
    }
    if (pathProblems.isNotEmpty) return null;
    final String path;
    try {
      path = template.render(brick.vars);
    } on Object catch (error) {
      issues.add(
        SmfIssue(
          'The path $template in the brick $name of $origin cannot be '
          'rendered: $error',
          origin: origin,
          path: template,
        ),
      );
      return null;
    }
    if (_pathProblem(path) case final problem?) {
      issues.add(
        SmfIssue(
          'The path $template in the brick $name of $origin renders to '
          '"$path", which $problem.',
          origin: origin,
          path: template,
        ),
      );
      return null;
    }
    final kind = brick.kind;
    if (origin case ModuleOrigin(:final module)
        when kind != null && !kind.allowsFile(module, path)) {
      issues.add(
        SmfIssue(
          'The module $module generates $path, where modules of the '
          '${kind.id} kind may not.',
          origin: origin,
          path: path,
        ),
      );
      return null;
    }
    return path;
  }

  /// The content of [file], the template [template] of [brick], rendered
  /// with mason if it is text with tags, or `null` after reporting why it
  /// cannot be rendered.
  ({List<int> bytes, bool isText})? _contentOf(
    _Brick brick,
    MasonBundledFile file,
    String template,
  ) {
    final bytes = base64.decode(file.data);
    final text = templateTextOf(file);
    if (text == null) return (bytes: bytes, isText: false);
    if (!masonTag.hasMatch(text)) return (bytes: bytes, isText: true);
    final _Brick(:origin, :name, :vars, :fragments) = brick;
    final scan = scanTemplate(template, text);
    if (!_readFragmentVariables(
      scan,
      template,
      brick: name,
      origin: origin,
      fragments: fragments,
      variables: variables,
      issues: issues,
    )) {
      return null;
    }
    final unset = unsetNames(scan, vars);
    if (unset.isNotEmpty) {
      issues.add(
        SmfIssue(
          'The template $template in the brick $name of $origin reads '
          '${unset.join(', ')}, which neither the brick nor a render hook '
          'of ${brick.owner} sets, so mustache would render nothing.',
          hint: 'Set every variable a template reads, to "" or false when '
              'there is nothing.',
          origin: origin,
          path: template,
        ),
      );
      return null;
    }
    // Stage 5 rendered the template once, and its variables are plain
    // data, which mustache renders.
    final rendered = _withoutEmptyLines(
      text,
      (tag) => texts[tag] == '' || fragments[tag]?.code == '',
    ).render(vars);
    return (bytes: utf8.encode(rendered), isText: true);
  }

  /// Whether [origin] generates [path] although another file of the app
  /// already has it, which it reports.
  bool _isGeneratedTwice(ContributionOrigin origin, String path) {
    // File systems that ignore case, as macOS and Windows do by default,
    // take paths that differ only in case for one file.
    final same = files.values
        .where((file) => file.path.toLowerCase() == path.toLowerCase())
        .firstOrNull;
    if (same == null) return false;
    final what = same.path == path
        ? path
        : '${same.path} and $path, one file where case does not matter';
    issues.add(
      SmfIssue(
        same.owner == origin
            ? '$origin generates $what twice; every file has one brick.'
            : 'Both ${same.owner} and $origin generate $what; every file '
                'has one brick.',
        origin: origin,
        path: path,
      ),
    );
    return true;
  }
}

/// [text] without the lines that hold nothing but a variable in three
/// braces that [isEmpty] says renders to nothing, such as the tag of a
/// socket that gets nothing, so that it leaves no blank line behind, such
/// as in a native file that the pipeline does not format.
String _withoutEmptyLines(String text, bool Function(String name) isEmpty) =>
    text.replaceAllMapped(
      _variableLine,
      (match) => isEmpty(match[1]!) ? '' : match[0]!,
    );

/// A line that holds nothing but a variable in three braces, with its line
/// break.
final RegExp _variableLine = RegExp(
  r'^[ \t]*\{\{\{\s*(\w+)\s*\}\}\}[ \t]*(?:\r?\n|$)',
  multiLine: true,
);

/// The problems with the variables that [template], the path of a file of
/// a brick of [owner], reads: one that neither the brick nor a render hook
/// of [owner] sets, among [vars], which mustache would render as nothing,
/// and a fragment variable among [fragments], whose code a path cannot
/// hold; the fragment variables it reads go to [read].
List<String> _pathVariableProblems(
  String template, {
  required ContributionOrigin owner,
  required Map<String, Object?> vars,
  required Map<String, Fragment> fragments,
  required void Function(String variable) read,
}) {
  if (!masonTag.hasMatch(template)) return const [];
  final scan = scanTemplate(template, template);
  final code = {
    for (final tag in scan.tags)
      if (fragments.containsKey(variableOf(tag.name))) variableOf(tag.name),
  }..forEach(read);
  final unset = unsetNames(scan, vars);
  final problems = <String>[];
  if (unset.isNotEmpty) {
    problems.add(
      'reads ${unset.join(', ')}, which neither the brick nor a render hook '
      'of $owner sets, so mustache would render nothing.',
    );
  }
  if (code.isNotEmpty) {
    final what = code.length == 1 ? 'variable' : 'variables';
    problems.add(
      'reads the fragment $what ${code.join(', ')}, but a path takes plain '
      'values only.',
    );
  }
  return problems;
}

/// Reads the fragment variables among [fragments] that [scan], the scan of
/// the template file [template] of the brick [brick] of [origin], reads:
/// records them as read, and their imports for the file, and reports how
/// the file reads them wrongly to [issues].
///
/// Returns `false` if the file reads one wrongly, so it is not rendered.
bool _readFragmentVariables(
  TemplateScan scan,
  String template, {
  required String brick,
  required ContributionOrigin origin,
  required Map<String, Fragment> fragments,
  required _VariableImports variables,
  required List<SmfIssue> issues,
}) {
  if (fragments.isEmpty) return true;
  final owner = ownerOf(origin);
  final reads = _fragmentReads(scan, fragments);
  // The template reads the variables, even if not as it should.
  for (final variable in reads.names) {
    variables.read.add((owner, variable));
  }
  for (final problem in reads.problems) {
    issues.add(
      SmfIssue(
        'The template $template in the brick $brick of $origin $problem',
        origin: origin,
        path: template,
      ),
    );
  }
  if (reads.problems.isNotEmpty) return false;
  for (final variable in reads.names) {
    final imports = fragments[variable]!.imports;
    if (imports.isEmpty) continue;
    if (!template.endsWith('.dart')) {
      issues.add(
        SmfIssue(
          'The template $template in the brick $brick of $origin is not '
          'Dart, but it reads the fragment variable $variable, whose '
          'imports can only go into a Dart file.',
          origin: origin,
          path: template,
        ),
      );
      continue;
    }
    variables.names.putIfAbsent((origin, template), () => {}).add(variable);
    variables.imports.putIfAbsent((origin, template), () => []).addAll([
      for (final import in imports) AddedImport(import, owner),
    ]);
  }
  return true;
}

/// The names of the variables and sections that the templates of the
/// bricks of [owner] read, those that this app leaves out included.
Set<String> _namesReadBy(Collection collection, ContributionOrigin owner) => {
      for (final collected in collection.all)
        if (collected.contribution case final BrickContribution brick
            when ownerOf(collected.origin) == owner)
          ..._namesReadIn(brick),
    };

/// The names of the variables and sections that the templates of [brick]
/// read.
Set<String> _namesReadIn(BrickContribution brick) => {
      for (final MapEntry(key: path, value: text)
          in templateFilesOf(brick).entries)
        if (masonTag.hasMatch(text))
          if (scanTemplate(path, text) case final scan) ...[
            for (final tag in scan.tags) variableOf(tag.name),
            for (final section in scan.sections) variableOf(section.name),
          ],
    };

/// The fragment variables among [fragments] that the template of [scan]
/// reads, and the problems with how it reads them: each must be read as it
/// is, `{{{name}}}`, which mustache does not escape, and outside mustache
/// sections, since the render hook decides what the variable holds, and the
/// imports of the fragment would otherwise go into the file for code that
/// is not there.
({Set<String> names, List<String> problems}) _fragmentReads(
  TemplateScan scan,
  Map<String, Fragment> fragments,
) {
  final names = <String>{};
  final problems = <String>[];
  for (final tag in scan.tags) {
    final name = variableOf(tag.name);
    if (!fragments.containsKey(name)) continue;
    names.add(name);
    if (!tag.triple || tag.name != name) {
      final how = tag.name != name ? 'as ${tag.name}' : 'without three braces';
      problems.add(
        'reads the fragment variable $name $how at line ${tag.line}; read a '
        'fragment of code as it is, {{{$name}}}.',
      );
    }
    if (tag.sections.isNotEmpty) {
      problems.add(
        'reads the fragment variable $name inside the mustache section '
        '${tag.sections.last} at line ${tag.line}; the render hook decides '
        'what the variable holds instead.',
      );
    }
  }
  for (final section in scan.sections) {
    final name = variableOf(section.name);
    if (!fragments.containsKey(name)) continue;
    problems.add(
      'opens a section over the fragment variable $name at line '
      '${section.line}; read a fragment of code as it is, {{{$name}}}.',
    );
  }
  return (names: names, problems: problems);
}

/// What is wrong with [path], a rendered path of a file of the app, or
/// `null` if it is a path inside the app.
String? _pathProblem(String path) {
  if (path.isEmpty) return 'is empty';
  if (path.startsWith('/') ||
      path.contains(r'\') ||
      RegExp('^[A-Za-z]:').hasMatch(path)) {
    return 'is not a relative path with forward slashes';
  }
  final segments = path.split('/');
  if (segments.any((segment) => segment.isEmpty || segment == '.')) {
    return 'has an empty or "." segment';
  }
  if (segments.contains('..')) return 'leaves the directory of the app';
  if (machineFileProblem(path) case final problem?) return problem;
  if (_entity.hasMatch(path)) {
    return 'has an HTML entity: mustache escapes variables in two braces, '
        'so a variable with a slash needs three';
  }
  return null;
}

/// An entity that mustache writes for `&`, `<`, `>`, `"`, `'` or `/` in a
/// variable in two braces.
final RegExp _entity = RegExp('&(?:amp|lt|gt|quot|#x27|#x2F);');
