import 'dart:convert';

import 'package:mason/mason.dart' show RenderTemplate;
import 'package:smf_contracts/lego_core.dart';
import 'package:smf_pipeline/src/access.dart';
import 'package:smf_pipeline/src/collector.dart';
import 'package:smf_pipeline/src/errors.dart';
import 'package:smf_pipeline/src/imports.dart';
import 'package:smf_pipeline/src/move.dart';
import 'package:smf_pipeline/src/order.dart';
import 'package:smf_pipeline/src/pubspec.dart';
import 'package:smf_pipeline/src/registry.dart';
import 'package:smf_pipeline/src/resolver.dart';
import 'package:smf_pipeline/src/templates.dart';
import 'package:smf_pipeline/src/validation.dart';

/// An import that the pipeline added to a file of the app for a fragment,
/// with who contributed the fragment.
final class AddedImport {
  /// Creates the record of [import], needed by [contributor].
  const AddedImport(this.import, this.contributor);

  /// The import, as the fragment gave it.
  final ImportRef import;

  /// Who contributed the fragment that needs it.
  final ContributionOrigin contributor;
}

/// A file of the app that stage 8 rendered.
final class RenderedFile {
  /// Creates the file at [path] with [bytes], generated by [owner].
  const RenderedFile({
    required this.path,
    required this.bytes,
    required this.owner,
    this.isText = true,
    this.addedImports = const [],
  });

  /// The path relative to the root of the app, with forward slashes.
  final String path;

  /// The content.
  final List<int> bytes;

  /// Whether the file is text, which mason renders, or binary, which it
  /// copies.
  final bool isText;

  /// Who generated the file: the owner of its brick.
  final ContributionOrigin owner;

  /// The imports the pipeline added to the file for the fragments of the
  /// sockets whose tags it holds, one for each fragment that needs it,
  /// resolved in the app: an import the file already had is not among
  /// them.
  final List<AddedImport> addedImports;

  /// The content as text.
  String get text => utf8.decode(bytes, allowMalformed: true);

  RenderedFile _withText(String text, List<AddedImport> addedImports) =>
      RenderedFile(
        path: path,
        bytes: utf8.encode(text),
        owner: owner,
        isText: isText,
        addedImports: addedImports,
      );
}

/// The app that stage 8 rendered, in memory.
final class RenderedApp {
  /// Creates the app of [files].
  RenderedApp(Iterable<RenderedFile> files)
      : files = Map.unmodifiable({
          for (final file
              in files.toList()..sort((a, b) => a.path.compareTo(b.path)))
            file.path: file,
        });

  /// The files by path, relative to the root of the app, sorted by path.
  final Map<String, RenderedFile> files;

  /// The text of every text file, by path.
  Map<String, String> get texts => {
        for (final file in files.values)
          if (file.isText) file.path: file.text,
      };

  /// Who generated each file, by path.
  Map<String, ContributionOrigin> get owners => {
        for (final file in files.values) file.path: file.owner,
      };
}

/// What the render hooks of the roles and their providers returned.
final class _HookOutput {
  /// The fragments that apply, each with its origin.
  final List<Collected> fragments = [];

  /// The brick variables of each owner: a module or a role template.
  final Map<ContributionOrigin, Map<String, Object?>> vars = {};
}

/// Stage 8 of the pipeline: renders the app in memory.
///
/// 1. Runs the render hooks of the templates and providers of the present
///    roles, with the results of [choices]. Their fragments follow the rules
///    of the contributions of their owner, and their brick variables must
///    not be reserved (see [isReservedVar]) or set twice for one owner.
/// 2. Orders the contributions of every socket, those of the render hooks
///    included (see [orderContributions]), and renders each socket into the
///    text of its tags. A socket that gets contributions but has no tag in
///    any brick is an error, since its code would be lost. The sockets of
///    the pipeline get the sections of the merged [pubspec], and the tags
///    of sockets that get nothing render to nothing: a line that holds
///    nothing but such a tag goes away with it.
/// 3. Renders every brick that applies with mason, with the variables of
///    [BrickContribution]: the names of the app, the presence flags of the
///    roles its owner provides, requires or uses, the tags, the variables of
///    its owner's render hooks and its own. A template that mason cannot
///    render, a path that leaves the app, and a path that two bricks
///    generate are errors.
/// 4. Adds the imports of each socket's fragments to the Dart file that
///    holds its tag; see [addImports].
///
/// Throws a [GenerationFailedException] with every problem found.
RenderedApp renderApp({
  required ModuleRegistry registry,
  required Resolution resolution,
  required Collection collection,
  required ModuleContext context,
  required Map<Role, Object?> choices,
  required MergedPubspec pubspec,
}) {
  final issues = <SmfIssue>[];
  void stopOnErrors() {
    final errors = [
      for (final issue in issues)
        if (issue.isError) issue,
    ];
    if (errors.isEmpty) return;
    throw GenerationFailedException(
      errors.length == 1
          ? 'The app cannot be rendered because of an error.'
          : 'The app cannot be rendered because of ${errors.length} errors.',
      issues: errors,
    );
  }

  final hooks = _runRenderHooks(
    registry: registry,
    resolution: resolution,
    collection: collection,
    context: context,
    choices: choices,
    issues: issues,
  );
  stopOnErrors();

  final tags = scanBricks(
    registry: registry,
    resolution: resolution,
    collection: collection,
  );
  final texts = _renderSockets(
    contributions: [
      ...collection.applyingOf<SocketContribution>(),
      ...hooks.fragments,
    ],
    resolution: resolution,
    tags: tags,
    issues: issues,
  );
  texts.texts.addAll(pubspecSocketTexts(pubspec));
  for (final MapEntry(key: socket, value: byName) in tags.found.entries) {
    for (final name in byName.keys) {
      if (texts.texts.containsKey(name)) continue;
      if (socket.kind case ValueSocket(required: true)) {
        issues.add(
          SmfIssue(
            'The $socket needs a value, but nothing contributes one.',
            origin: byName[name]!.first.$2,
          ),
        );
        continue;
      }
      // A socket that gets nothing renders to nothing.
      texts.texts[name] = '';
    }
  }
  stopOnErrors();

  final files = <String, RenderedFile>{};
  // The path each template file rendered to, by owner and template path.
  final renderedPaths = <(ContributionOrigin, String), String>{};
  for (final collected in collection.applyingOf<BrickContribution>()) {
    _renderBrick(
      collected,
      registry: registry,
      resolution: resolution,
      context: context,
      texts: texts.texts,
      hookVars: hooks.vars,
      files: files,
      renderedPaths: renderedPaths,
      issues: issues,
    );
  }
  stopOnErrors();

  for (final MapEntry(key: (owner, template), value: added)
      in texts.imports.entries) {
    // Only text files hold tags, and every brick rendered.
    final path = renderedPaths[(owner, template)] ??
        (throw StateError('$template of $owner was not rendered.'));
    try {
      files[path] = _withImports(files[path]!, added, context.appName);
    } on ImportTargetException catch (error) {
      final sockets = texts.socketsByTemplate[(owner, template)]!;
      issues.add(
        SmfIssue(
          'The imports of the ${sockets.join(', ')} cannot go into $path, '
          'which holds ${sockets.length == 1 ? 'its tag' : 'their tags'}: '
          '${error.reason}.',
          hint: 'Put the tag into the library file.',
          origin: owner,
          path: path,
        ),
      );
    }
  }
  stopOnErrors();
  return RenderedApp(files.values);
}

/// [file] with the imports of [added] that it does not have yet, and with
/// them recorded, resolved in the app of [appName].
///
/// Throws an [ImportTargetException] if the file cannot have imports.
RenderedFile _withImports(
  RenderedFile file,
  List<AddedImport> added,
  String appName,
) {
  final result = addImports(
    file.text,
    path: file.path,
    imports: [for (final import in added) import.import],
    appName: appName,
  );
  String keyOf(ImportRef import) =>
      '${import.resolveUri(appName)} as ${import.prefix}';
  final inserted = {for (final import in result.added) keyOf(import)};
  return file._withText(result.text, [
    for (final import in added)
      if (inserted.contains(keyOf(import.import)))
        AddedImport(
          ImportRef(
            import.import.resolveUri(appName),
            prefix: import.import.prefix,
            show: import.import.show,
          ),
          import.contributor,
        ),
  ]);
}

/// Runs the render hooks of the templates and providers of the present
/// roles and checks what they return.
_HookOutput _runRenderHooks({
  required ModuleRegistry registry,
  required Resolution resolution,
  required Collection collection,
  required ModuleContext context,
  required Map<Role, Object?> choices,
  required List<SmfIssue> issues,
}) {
  final present = resolution.presentRoles;
  final request = hookRequest(
    registry: registry,
    resolution: resolution,
    collection: collection,
    context: context,
    choices: choices,
  );
  final output = _HookOutput();

  void add(ContributionOrigin origin, RoleOutput Function() render) {
    final RoleOutput result;
    try {
      result = render();
    } on Object catch (error) {
      issues.add(
        SmfIssue('The render hook of $origin failed: $error', origin: origin),
      );
      return;
    }
    final vars = output.vars.putIfAbsent(origin, () => {});
    for (final MapEntry(:key, :value) in result.vars.entries) {
      if (isReservedVar(key)) {
        issues.add(
          SmfIssue(
            'The render hook of $origin sets the brick variable $key, which '
            'the pipeline sets itself.',
            origin: origin,
          ),
        );
      } else if (vars.containsKey(key)) {
        issues.add(
          SmfIssue(
            'Two render hooks of $origin set the brick variable $key.',
            origin: origin,
          ),
        );
      } else {
        vars[key] = value;
      }
    }
    for (final name in strippedVars(result.vars)) {
      issues.add(
        SmfIssue(
          'The brick variable $name of the render hook of $origin has a '
          'backslash before a line break or a non-ASCII character, which '
          'mason removes.',
          origin: origin,
        ),
      );
    }
    for (final name in nonPlainVars(result.vars)) {
      issues.add(
        SmfIssue(
          'The brick variable $name of the render hook of $origin is not '
          'plain data: strings, numbers, booleans, and lists and maps of '
          'them.',
          origin: origin,
        ),
      );
    }
    for (final fragment in result.fragments) {
      final socket = fragment.socket;
      final collected = Collected(
        fragment.withOrigin(origin),
        origin,
        applies: fragment.when.every(present.contains) &&
            (socket.role == null || present.contains(socket.role)),
      );
      issues.addAll(contributionIssues(collected, registry, resolution));
      if (collected.applies) output.fragments.add(collected);
    }
  }

  for (final role in present) {
    // The input's runtime type argument is the role's data type, which the
    // hooks of the role's template and providers take.
    final input = role.hookInput(request);
    if (role.template case final template?) {
      add(RoleTemplateOrigin(role), () => template.render(input));
    }
    for (final module in resolution.providersOf(role)) {
      final provider = Resolution.providerObject(module, role);
      add(module.origin, () => provider.render(input));
    }
  }
  return output;
}

/// The rendered sockets of an app: the text of every tag, and the imports
/// for each template file that holds a tag of a socket with imports.
final class _SocketTexts {
  /// The text of each tag.
  final Map<String, String> texts = {};

  /// The imports for each template file, by owner and template path.
  final Map<(ContributionOrigin, String), List<AddedImport>> imports = {};

  /// The sockets whose tags each of those template files holds.
  final Map<(ContributionOrigin, String), List<SocketRef>> socketsByTemplate =
      {};
}

/// Orders [contributions] by socket and renders each socket.
_SocketTexts _renderSockets({
  required List<Collected> contributions,
  required Resolution resolution,
  required BrickTags tags,
  required List<SmfIssue> issues,
}) {
  final result = _SocketTexts();
  final bySocket = <SocketRef, List<Collected>>{};
  for (final collected in contributions) {
    final socket = (collected.contribution as SocketContribution).socket;
    bySocket.putIfAbsent(socket, () => []).add(collected);
  }

  for (final MapEntry(key: socket, value: collected) in bySocket.entries) {
    final order = orderContributions(collected, resolution);
    if (order.cycle.isNotEmpty) {
      issues.add(
        SmfIssue(
          'The contributors to the $socket cannot be ordered, because their '
          'order edges form a cycle: ${order.cycle.join(', ')}.',
          hint: 'Run with --explain to see the edges.',
        ),
      );
      continue;
    }
    final place = tags.placeOf(socket);
    if (place == null) {
      final contributors = {
        for (final collected in order.contributions) collected.origin,
      };
      issues.add(
        SmfIssue(
          '${contributors.join(', ')} '
          '${contributors.length == 1 ? 'contributes' : 'contribute'} to '
          'the $socket, but no template of the app has its tag '
          '${socket.tags.join(', ')}, so what they contribute would be lost.',
          origin: contributors.first,
        ),
      );
      continue;
    }
    try {
      result.texts.addAll(
        socket.render([
          for (final collected in order.contributions)
            collected.contribution as SocketContribution,
        ]),
      );
    } on MergeConflict catch (conflict) {
      issues.add(
        SmfIssue(
          'The contributions to the $socket conflict: $conflict.',
          origin: conflict.incomingOrigin,
        ),
      );
      continue;
    } on Object catch (error) {
      issues.add(SmfIssue('The $socket cannot be rendered: $error.'));
      continue;
    }
    if (!socket.kind.carriesImports) continue;
    final (tag, owner) = place;
    final key = (owner, tag.path);
    result.socketsByTemplate.putIfAbsent(key, () => []).add(socket);
    final imports = result.imports.putIfAbsent(key, () => []);
    for (final collected in order.contributions) {
      final fragment = (collected.contribution as SocketContribution).fragment;
      for (final import in fragment?.imports ?? const <ImportRef>[]) {
        imports.add(AddedImport(import, collected.origin));
      }
    }
  }
  return result;
}

/// Renders the files of the brick of [collected] into [files].
void _renderBrick(
  Collected collected, {
  required ModuleRegistry registry,
  required Resolution resolution,
  required ModuleContext context,
  required Map<String, String> texts,
  required Map<ContributionOrigin, Map<String, Object?>> hookVars,
  required Map<String, RenderedFile> files,
  required Map<(ContributionOrigin, String), String> renderedPaths,
  required List<SmfIssue> issues,
}) {
  final origin = collected.origin;
  final brick = collected.contribution as BrickContribution;
  final name = brick.bundle.name;
  // A variant's bricks belong to its module and get the module's variables.
  final owner = ownerOf(origin);
  final fromHooks = hookVars[owner] ?? const <String, Object?>{};
  final present = resolution.presentRoles;
  final vars = <String, Object?>{
    'app_name': context.appName,
    'org_name': context.orgName,
    for (final role in rolesOf(origin, registry, resolution).access)
      role.presenceFlag: present.contains(role),
    ...texts,
    ...fromHooks,
  };
  for (final MapEntry(:key, :value) in brick.vars.entries) {
    if (fromHooks.containsKey(key)) {
      issues.add(
        SmfIssue(
          'The brick $name of $origin sets the variable $key, which a render '
          'hook of $owner sets too.',
          origin: origin,
        ),
      );
    }
    vars[key] = value;
  }

  final kind = switch (origin) {
    ModuleOrigin(:final module) => resolution.module(module)?.descriptor.kind,
    _ => null,
  };
  for (final file in brick.bundle.files) {
    final template = file.path.replaceAll(r'\', '/');
    final String path;
    try {
      path = template.render(vars);
    } on Object catch (error) {
      issues.add(
        SmfIssue(
          'The path $template in the brick $name of $origin cannot be '
          'rendered: $error',
          origin: origin,
          path: template,
        ),
      );
      continue;
    }
    if (_pathProblem(path) case final problem?) {
      issues.add(
        SmfIssue(
          'The path $template in the brick $name of $origin renders to '
          '"$path", which $problem.',
          origin: origin,
          path: template,
        ),
      );
      continue;
    }
    if (origin case ModuleOrigin(:final module)
        when kind != null && !kind.allowsFile(module, path)) {
      issues.add(
        SmfIssue(
          'The module $module generates $path, where modules of the '
          '${kind.id} kind may not.',
          origin: origin,
          path: path,
        ),
      );
      continue;
    }

    var bytes = base64.decode(file.data) as List<int>;
    final text = templateTextOf(file);
    final isText = text != null;
    if (text != null) {
      final unset = masonTag.hasMatch(text)
          ? unsetNames(scanTemplate(template, text), vars)
          : const <String>[];
      if (unset.isNotEmpty) {
        issues.add(
          SmfIssue(
            'The template $template in the brick $name of $origin reads '
            '${unset.join(', ')}, which neither the brick nor a render hook '
            'of $owner sets, so mustache would render nothing.',
            hint: 'Set every variable a template reads, to "" or false when '
                'there is nothing.',
            origin: origin,
            path: template,
          ),
        );
        continue;
      }
      if (masonTag.hasMatch(text)) {
        try {
          bytes = utf8.encode(
            _withoutEmptySocketLines(text, texts).render(vars),
          );
        } on Object catch (error) {
          issues.add(
            SmfIssue(
              'The template $template in the brick $name of $origin cannot '
              'be rendered: $error',
              origin: origin,
              path: template,
            ),
          );
          continue;
        }
      }
    }
    // File systems that ignore case, as macOS and Windows do by default,
    // take paths that differ only in case for one file.
    final same = files.values
        .where((file) => file.path.toLowerCase() == path.toLowerCase())
        .firstOrNull;
    if (same != null) {
      final what = same.path == path
          ? path
          : '${same.path} and $path, one file where case does not matter';
      issues.add(
        SmfIssue(
          same.owner == origin
              ? '$origin generates $what twice; every file has one brick.'
              : 'Both ${same.owner} and $origin generate $what; every file '
                  'has one brick.',
          origin: origin,
          path: path,
        ),
      );
      continue;
    }
    files[path] = RenderedFile(
      path: path,
      bytes: bytes,
      owner: origin,
      isText: isText,
    );
    renderedPaths[(origin, template)] = path;
  }
}

/// [text] without the lines that hold nothing but the tag of a socket whose
/// text in [sockets] is empty, so that an empty socket leaves no blank line
/// behind, such as in a native file that the pipeline does not format.
String _withoutEmptySocketLines(String text, Map<String, String> sockets) =>
    text.replaceAllMapped(
      _socketLine,
      (match) => sockets[match[1]] == '' ? '' : match[0]!,
    );

/// A line that holds nothing but the tag of a socket, with its line break.
final RegExp _socketLine = RegExp(
  r'^[ \t]*\{\{\{(smf_\w+)\}\}\}[ \t]*(?:\r?\n|$)',
  multiLine: true,
);

/// What is wrong with [path], a rendered path of a file of the app, or
/// `null` if it is a path inside the app.
String? _pathProblem(String path) {
  if (path.isEmpty) return 'is empty';
  if (path.startsWith('/') ||
      path.contains(r'\') ||
      RegExp('^[A-Za-z]:').hasMatch(path)) {
    return 'is not a relative path with forward slashes';
  }
  final segments = path.split('/');
  if (segments.any((segment) => segment.isEmpty || segment == '.')) {
    return 'has an empty or "." segment';
  }
  if (segments.contains('..')) return 'leaves the directory of the app';
  for (final tool in flutterToolFiles) {
    if (path == tool || path.startsWith('$tool/')) {
      return "is written by Flutter's tools, which the pipeline does not move "
          'with the app';
    }
  }
  if (_entity.hasMatch(path)) {
    return 'has an HTML entity: mustache escapes variables in two braces, '
        'so a variable with a slash needs three';
  }
  return null;
}

/// An entity that mustache writes for `&`, `<`, `>`, `"`, `'` or `/` in a
/// variable in two braces.
final RegExp _entity = RegExp('&(?:amp|lt|gt|quot|#x27|#x2F);');
