import 'dart:convert';
import 'dart:io';

import 'package:mason/mason.dart';
import 'package:path/path.dart' as p;
import 'package:smf_contracts/smf_contracts.dart';
import 'package:smf_contribution_engine/smf_contribution_engine.dart';
import 'package:smf_flutter_cli/constants/smf_modules.dart';
import 'package:yaml_edit/yaml_edit.dart';

/// Modules `smf create` always adds (see CreateCommand.run).
const coreModuleKeys = <String>[kFlutterCoreModule, kContractsModule];

/// The app name as the smf_cli_brick pre_gen hook hands it to bricks.
const appName = 'contract_app';

/// Every registered module the [profile] supports, keyed by registry key.
Map<String, IModuleCodeContributor> modulesFor(ModuleProfile profile) {
  return {
    for (final entry in smfModules.entries)
      if (entry.value.supports(profile)) entry.key: entry.value.create(profile),
  };
}

/// The vars runCli renders every brick with: its coreVars after the
/// smf_cli_brick pre_gen hook ran for app "Contract App" in org com.example.
Map<String, dynamic> cliBrickVars({
  required String outputDirectory,
  required Iterable<IModuleCodeContributor> modules,
}) {
  final names = modules.map((m) => "'${m.moduleDescriptor.name}'").join(',');
  return <String, dynamic>{
    kWorkingDirectory: p.join(outputDirectory, appName),
    'modules': '[$names]',
    'app_name': appName,
    'org_name': 'com.example',
    'strict_mode': false,
    'android_application_id': 'com.example.contract_app',
    'ios_application_id': 'com.example.contract-app',
    'android_namespace': 'com.example.contract_app',
  };
}

/// Keys of the modules a project with module [key] contains: the module, its
/// transitive dependencies and the core modules.
Set<String> dependencyClosure(
  String key,
  Map<String, IModuleCodeContributor> modules,
) {
  final closure = <String>{};
  void visit(String name) {
    final module = modules[name];
    if (module == null || !closure.add(name)) return;
    module.moduleDescriptor.dependsOn.forEach(visit);
  }

  [key, ...coreModuleKeys].forEach(visit);
  return closure;
}

/// Decodes bundled files or hooks: their text by path, null when binary.
Map<String, String?> decodeBundleFiles(List<MasonBundledFile> files) {
  return {
    for (final file in files)
      file.path: switch ((file.type, base64.decode(file.data))) {
        ('text', final bytes) => utf8.decode(bytes),
        _ => null,
      },
  };
}

/// Path fragments of files that are machine-local or generated by Flutter,
/// Xcode, Gradle, pub or the OS and must never ship in a brick.
const machineLocalPathFragments = [
  '/android/local.properties',
  '/Generated.xcconfig',
  '/flutter_export_environment.sh',
  '/xcuserdata/',
  '/.dart_tool/',
  'GeneratedPluginRegistrant',
  '/ephemeral/',
  '/.DS_Store',
  '/build/',
  '/pubspec.lock',
];

bool isMachineLocalPath(String path) {
  final normalized = '/${path.replaceAll(r'\', '/')}';
  return machineLocalPathFragments.any(normalized.contains);
}

/// A brick rendered by mason into its own output directory.
class RenderedBrick {
  const RenderedBrick({required this.files, required this.outsideAppRoot});

  /// Rendered files by posix path relative to the app root, with their text
  /// (null when binary).
  final Map<String, String?> files;

  /// Rendered files that landed outside the app root.
  final List<String> outsideAppRoot;
}

/// Renders [brick] like BrickGenerator does, but without running its hooks.
Future<RenderedBrick> renderBrick(
  BrickContribution brick, {
  required Directory outputDirectory,
  required Map<String, dynamic> coreVars,
}) async {
  final generator = await MasonGenerator.fromBundle(brick.bundle);
  await generator.generate(
    DirectoryGeneratorTarget(outputDirectory),
    vars: {...coreVars, ...?brick.vars},
    fileConflictResolution: FileConflictResolution.overwrite,
  );

  final appRoot = p.join(outputDirectory.path, appName);
  final files = <String, String?>{};
  final outside = <String>[];
  for (final file in outputDirectory.listSync(recursive: true)) {
    if (file is! File) continue;
    if (!p.isWithin(appRoot, file.path)) {
      outside.add(p.relative(file.path, from: outputDirectory.path));
      continue;
    }

    final relative = p.posix.joinAll(
      p.split(p.relative(file.path, from: appRoot)),
    );
    try {
      files[relative] = utf8.decode(file.readAsBytesSync());
    } on FormatException {
      files[relative] = null;
    }
  }

  return RenderedBrick(files: files, outsideAppRoot: outside);
}

/// A `name: constraint` pub dependency as declared in a ModuleDescriptor.
typedef PubSpec = ({String name, VersionConstraint constraint});

final _pubSpecPattern = RegExp(r'^([^:\s]+)\s*:\s*(\S.*)$');
final _pubPackageName = RegExp(r'^[a-z_][a-z0-9_]*$');

const _dartReservedWords = {
  'assert',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'default',
  'do',
  'else',
  'enum',
  'extends',
  'false',
  'final',
  'finally',
  'for',
  'if',
  'in',
  'is',
  'new',
  'null',
  'rethrow',
  'return',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'var',
  'void',
  'while',
  'with',
};

/// Parses [spec], throwing a [FormatException] when it is not a valid pub
/// package name followed by a valid version constraint.
PubSpec parsePubSpec(String spec) {
  final match = _pubSpecPattern.firstMatch(spec.trim());
  if (match == null) {
    throw FormatException('Expected "package: constraint"', spec);
  }

  final name = match[1]!;
  if (!_pubPackageName.hasMatch(name) || _dartReservedWords.contains(name)) {
    throw FormatException('Invalid pub package name "$name"', spec);
  }

  return (name: name, constraint: VersionConstraint.parse(match[2]!.trim()));
}

/// Names of the packages listed under `dependencies` in [pubspec].
Set<String> pubspecDependencies(String pubspec) {
  final dependencies = YamlEditor(pubspec).parseAt(['dependencies']).value;
  if (dependencies is! Map) return {};
  return dependencies.keys.map((key) => '$key').toSet();
}

/// Where an import, export or part uri points to.
typedef UriTarget = ({String? appFile, String? package});

/// Resolves [uri] from the app file [fromFile]: to a file of the generated
/// app (posix path relative to the app root), to another package, or to
/// neither for `dart:` libraries.
///
/// Brick templates end up importing `package:contract_app/...`; imports in
/// DSL and patch contributions use `{{app_name_sc}}`, which mustachex renders
/// to the same package.
UriTarget resolveUri(String uri, {String fromFile = 'lib/main.dart'}) {
  if (uri.startsWith('dart:')) return (appFile: null, package: null);

  if (uri.startsWith('package:')) {
    final slash = uri.indexOf('/');
    final package = uri.substring('package:'.length, slash);
    if (package == appName || package == '{{app_name_sc}}') {
      return (appFile: 'lib/${uri.substring(slash + 1)}', package: null);
    }
    return (appFile: null, package: package);
  }

  final path = p.posix.normalize(p.posix.join(p.posix.dirname(fromFile), uri));
  return (appFile: path, package: null);
}

final _dartDirective = RegExp(
  r'''^\s*(?:import|export|part)\s+['"]([^'"]+)['"]''',
  multiLine: true,
);

/// Uris of the import, export and part directives in [source].
Iterable<String> directiveUris(String source) {
  return _dartDirective.allMatches(source).map((m) => m[1]!);
}

/// The uri of a single import statement such as `Import.resolve()` returns.
String statementUri(String statement) {
  return RegExp('''['"]([^'"]+)['"]''').firstMatch(statement)![1]!;
}

/// Every import statement a module hands to the DSL generators.
List<String> dslImportStatements(IModuleCodeContributor module) {
  Iterable<Import> guardImports(List<RouteGuard> guards) =>
      guards.expand((g) => g.bindings.values).expand((b) => b.imports);

  Iterable<Import> routeImports(BaseRoute route) => [
        ...route.imports,
        ...guardImports(route.guards),
        if (route is NestedRoute) ...route.children.expand(routeImports),
      ];

  return [
    ...module.di.expand((group) => group.imports),
    ...module.routes.routes.expand(routeImports),
    ...guardImports(module.routes.coreGuards),
  ].map((import) => import.resolve()).toList();
}

/// Import statements a module's shared file patches insert.
List<String> contributionImportStatements(IModuleCodeContributor module) {
  return module.sharedFileContributions
      .whereType<InsertImport>()
      .map((c) => c.import)
      .toList();
}

/// All routes of [group], including the children of nested routes.
Iterable<Route> allRoutes(RouteGroup group) {
  return group.routes.expand(
    (route) => [
      if (route is Route) route,
      if (route is NestedRoute) ...route.children,
    ],
  );
}
