// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, implicit_dynamic_list_literal, implicit_dynamic_map_literal, inference_failure_on_collection_literal

import 'package:mason/mason.dart';

final firebaseCrashlyticsBundle = MasonBundle.fromJson(<String, dynamic>{
  "files": [
    {
      "path": "lib/core/crash_reporting/crashlytics_crash_reporter.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmZpcmViYXNlX2NyYXNobHl0aWNzL2ZpcmViYXNlX2NyYXNobHl0aWNzLmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6Zmx1dHRlci9mb3VuZGF0aW9uLmRhcnQnOwoKaW1wb3J0ICdjcmFzaF9yZXBvcnRlci5kYXJ0JzsKCi8vLyBDcmVhdGVzIGEgY3Jhc2ggcmVwb3J0ZXIgdGhhdCByZXBvcnRzIHRvIEZpcmViYXNlIENyYXNobHl0aWNzLCB3aGljaAovLy8gbmVlZHMgRmlyZWJhc2UgdG8gYmUgaW5pdGlhbGl6ZWQuCi8vLwovLy8gVGhlIGFwcCBoYXMgb25lIGNyYXNoIHJlcG9ydGVyLCB3aGljaCBgY3JlYXRlQ3Jhc2hSZXBvcnRlcigpYCByZXR1cm5zIGFuZAovLy8gd2hpY2ggZm9yd2FyZHMgZXZlcnkgcmVwb3J0IHRvIHRoaXMgb25lLgpDcmFzaFJlcG9ydGVyIGNyZWF0ZUNyYXNobHl0aWNzQ3Jhc2hSZXBvcnRlcigpID0+CiAgICBDcmFzaGx5dGljc0NyYXNoUmVwb3J0ZXIoRmlyZWJhc2VDcmFzaGx5dGljcy5pbnN0YW5jZSk7CgovLy8gUmVwb3J0cyB0aGUgZXJyb3JzIG9mIHRoZSBhcHAgdG8gRmlyZWJhc2UgQ3Jhc2hseXRpY3MuCi8vLwovLy8gSXQgcHJpbnRzIG5vdGhpbmc6IHRoZSBoYW5kbGVycyB0aGF0IGBpbnN0YWxsQ3Jhc2hSZXBvcnRpbmcoKWAgaW5zdGFsbHMKLy8vIGFscmVhZHkgc2hvdyBlYWNoIGVycm9yIHRoZXkgcmVwb3J0LCB3aGVyZSBDcmFzaGx5dGljcyB3b3VsZCBwcmVzZW50Ci8vLyBlYWNoIGVycm9yIG9mIEZsdXR0ZXIgYWdhaW4gYW5kLCBpbiBkZWJ1ZyBtb2RlLCBwcmludCBlYWNoIHJlcG9ydC4gU28gYW4KLy8vIGVycm9yIHRoYXQgdGhlIGNvZGUgb2YgdGhlIGFwcCByZXBvcnRzIGl0c2VsZiBpcyBub3QgcHJpbnRlZCBlaXRoZXIuCmZpbmFsIGNsYXNzIENyYXNobHl0aWNzQ3Jhc2hSZXBvcnRlciBpbXBsZW1lbnRzIENyYXNoUmVwb3J0ZXIgewogIC8vLyBDcmVhdGVzIHRoZSByZXBvcnRlciBvbiB0aGUgZ2l2ZW4gW0ZpcmViYXNlQ3Jhc2hseXRpY3NdLgogIENyYXNobHl0aWNzQ3Jhc2hSZXBvcnRlcih0aGlzLl9jcmFzaGx5dGljcyk7CgogIGZpbmFsIEZpcmViYXNlQ3Jhc2hseXRpY3MgX2NyYXNobHl0aWNzOwoKICBAb3ZlcnJpZGUKICBGdXR1cmU8dm9pZD4gcmVjb3JkRXJyb3IoCiAgICBPYmplY3QgZXJyb3IsCiAgICBTdGFja1RyYWNlPyBzdGFja1RyYWNlLCB7CiAgICBib29sIGZhdGFsID0gZmFsc2UsCiAgICBTdHJpbmc/IHJlYXNvbiwKICB9KSA9PgogICAgICBfY3Jhc2hseXRpY3MucmVjb3JkRXJyb3IoCiAgICAgICAgZXJyb3IsCiAgICAgICAgc3RhY2tUcmFjZSwKICAgICAgICByZWFzb246IHJlYXNvbiwKICAgICAgICBwcmludERldGFpbHM6IGZhbHNlLAogICAgICAgIGZhdGFsOiBmYXRhbCwKICAgICAgKTsKCiAgLy8vIFJlcG9ydHMgd2hhdCBbRmlyZWJhc2VDcmFzaGx5dGljcy5yZWNvcmRGbHV0dGVyRXJyb3JdIHJlcG9ydHMsIHdpdGhvdXQKICAvLy8gcHJlc2VudGluZyB0aGUgZXJyb3IgYXMgaXQgYWxzbyBkb2VzLgogIEBvdmVycmlkZQogIEZ1dHVyZTx2b2lkPiByZWNvcmRGbHV0dGVyRXJyb3IoCiAgICBGbHV0dGVyRXJyb3JEZXRhaWxzIGRldGFpbHMsIHsKICAgIGJvb2wgZmF0YWwgPSBmYWxzZSwKICB9KSA9PgogICAgICBfY3Jhc2hseXRpY3MucmVjb3JkRXJyb3IoCiAgICAgICAgZGV0YWlscy5leGNlcHRpb25Bc1N0cmluZygpLAogICAgICAgIGRldGFpbHMuc3RhY2ssCiAgICAgICAgcmVhc29uOiBkZXRhaWxzLmNvbnRleHQKICAgICAgICAgICAgPy50b1N0cmluZ0RlZXAobWluTGV2ZWw6IERpYWdub3N0aWNMZXZlbC5pbmZvKQogICAgICAgICAgICAudHJpbSgpLAogICAgICAgIGluZm9ybWF0aW9uOiBkZXRhaWxzLmluZm9ybWF0aW9uQ29sbGVjdG9yPy5jYWxsKCkgPz8gY29uc3QgW10sCiAgICAgICAgcHJpbnREZXRhaWxzOiBmYWxzZSwKICAgICAgICBmYXRhbDogZmF0YWwsCiAgICAgICk7CgogIEBvdmVycmlkZQogIEZ1dHVyZTx2b2lkPiBsb2coU3RyaW5nIG1lc3NhZ2UpID0+IF9jcmFzaGx5dGljcy5sb2cobWVzc2FnZSk7CgogIC8vLyBTZXRzIHRoZSBpZCBvZiB0aGUgdXNlciwgb3IgY2xlYXJzIGl0IHdpdGggYG51bGxgLCB3aGljaCBDcmFzaGx5dGljcwogIC8vLyBkb2VzIHdpdGggYW4gZW1wdHkgaWQuCiAgQG92ZXJyaWRlCiAgRnV0dXJlPHZvaWQ+IHNldFVzZXJJZChTdHJpbmc/IHVzZXJJZCkgPT4KICAgICAgX2NyYXNobHl0aWNzLnNldFVzZXJJZGVudGlmaWVyKHVzZXJJZCA/PyAnJyk7Cn0K",
      "type": "text"
    }
  ],
  "hooks": [],
  "name": "firebase_crashlytics",
  "description":
      "The crash reporting of an SMF app with Firebase Crashlytics: the crash reporter on FirebaseCrashlytics.",
  "version": "0.1.0+1",
  "environment": {"mason": "^0.1.1"},
  "vars": {}
});
