// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, implicit_dynamic_list_literal, implicit_dynamic_map_literal, inference_failure_on_collection_literal

import 'package:mason/mason.dart';

final firebaseCrashlyticsBundle = MasonBundle.fromJson(<String, dynamic>{
  "files": [
    {
      "path": "lib/core/crash_reporting/crashlytics_crash_reporter.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmZpcmViYXNlX2NyYXNobHl0aWNzL2ZpcmViYXNlX2NyYXNobHl0aWNzLmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6Zmx1dHRlci9mb3VuZGF0aW9uLmRhcnQnOwoKaW1wb3J0ICdjcmFzaF9yZXBvcnRlci5kYXJ0JzsKCi8vLyBDcmVhdGVzIGEgY3Jhc2ggcmVwb3J0ZXIgdGhhdCByZXBvcnRzIHRvIEZpcmViYXNlIENyYXNobHl0aWNzLCB3aGljaAovLy8gbmVlZHMgRmlyZWJhc2UgdG8gYmUgaW5pdGlhbGl6ZWQuCi8vLwovLy8gVGhlIGFwcCBoYXMgb25lIGNyYXNoIHJlcG9ydGVyLCB3aGljaCBgY3JlYXRlQ3Jhc2hSZXBvcnRlcigpYCByZXR1cm5zIGFuZAovLy8gd2hpY2ggZm9yd2FyZHMgZXZlcnkgcmVwb3J0IHRvIHRoaXMgb25lLgpDcmFzaFJlcG9ydGVyIGNyZWF0ZUNyYXNobHl0aWNzQ3Jhc2hSZXBvcnRlcigpID0+CiAgICBDcmFzaGx5dGljc0NyYXNoUmVwb3J0ZXIoRmlyZWJhc2VDcmFzaGx5dGljcy5pbnN0YW5jZSk7CgovLy8gUmVwb3J0cyB0aGUgZXJyb3JzIG9mIHRoZSBhcHAgdG8gRmlyZWJhc2UgQ3Jhc2hseXRpY3MuCi8vLwovLy8gSXQgcHJpbnRzIG5vdGhpbmcuIE9mIHRoZSBlcnJvcnMgdGhhdCBgaW5zdGFsbENyYXNoUmVwb3J0aW5nKClgIHJlcG9ydHMsCi8vLyBGbHV0dGVyIGFscmVhZHkgcHJlc2VudHMgdGhvc2UgaXQgY2F0Y2hlcywgaW4gZXZlcnkgbW9kZSwgYW5kIGluIGRlYnVnCi8vLyBtb2RlIHRoZSBlbmdpbmUgcHJpbnRzIHRoZSBvdGhlcnMsIHdoaWxlIENyYXNobHl0aWNzIHdvdWxkIHByZXNlbnQgZWFjaAovLy8gZXJyb3Igb2YgRmx1dHRlciBhZ2FpbiBhbmQsIGluIGRlYnVnIG1vZGUsIHByaW50IGVhY2ggcmVwb3J0LiBTbyBhbgovLy8gZXJyb3IgdGhhdCB0aGUgY29kZSBvZiB0aGUgYXBwIHJlcG9ydHMgaXRzZWxmIGlzIG5vdCBwcmludGVkIGVpdGhlci4KZmluYWwgY2xhc3MgQ3Jhc2hseXRpY3NDcmFzaFJlcG9ydGVyIGltcGxlbWVudHMgQ3Jhc2hSZXBvcnRlciB7CiAgLy8vIENyZWF0ZXMgdGhlIHJlcG9ydGVyIG9uIHRoZSBnaXZlbiBbRmlyZWJhc2VDcmFzaGx5dGljc10uCiAgQ3Jhc2hseXRpY3NDcmFzaFJlcG9ydGVyKHRoaXMuX2NyYXNobHl0aWNzKTsKCiAgZmluYWwgRmlyZWJhc2VDcmFzaGx5dGljcyBfY3Jhc2hseXRpY3M7CgogIEBvdmVycmlkZQogIEZ1dHVyZTx2b2lkPiByZWNvcmRFcnJvcigKICAgIE9iamVjdCBlcnJvciwKICAgIFN0YWNrVHJhY2U/IHN0YWNrVHJhY2UsIHsKICAgIGJvb2wgZmF0YWwgPSBmYWxzZSwKICAgIFN0cmluZz8gcmVhc29uLAogIH0pID0+CiAgICAgIF9jcmFzaGx5dGljcy5yZWNvcmRFcnJvcigKICAgICAgICBlcnJvciwKICAgICAgICBzdGFja1RyYWNlLAogICAgICAgIHJlYXNvbjogcmVhc29uLAogICAgICAgIHByaW50RGV0YWlsczogZmFsc2UsCiAgICAgICAgZmF0YWw6IGZhdGFsLAogICAgICApOwoKICAvLy8gUmVwb3J0cyB3aGF0IFtGaXJlYmFzZUNyYXNobHl0aWNzLnJlY29yZEZsdXR0ZXJFcnJvcl0gcmVwb3J0cywgd2l0aG91dAogIC8vLyBwcmVzZW50aW5nIHRoZSBlcnJvciBhcyBpdCBhbHNvIGRvZXMuCiAgQG92ZXJyaWRlCiAgRnV0dXJlPHZvaWQ+IHJlY29yZEZsdXR0ZXJFcnJvcigKICAgIEZsdXR0ZXJFcnJvckRldGFpbHMgZGV0YWlscywgewogICAgYm9vbCBmYXRhbCA9IGZhbHNlLAogIH0pID0+CiAgICAgIF9jcmFzaGx5dGljcy5yZWNvcmRFcnJvcigKICAgICAgICBkZXRhaWxzLmV4Y2VwdGlvbkFzU3RyaW5nKCksCiAgICAgICAgZGV0YWlscy5zdGFjaywKICAgICAgICByZWFzb246IGRldGFpbHMuY29udGV4dAogICAgICAgICAgICA/LnRvU3RyaW5nRGVlcChtaW5MZXZlbDogRGlhZ25vc3RpY0xldmVsLmluZm8pCiAgICAgICAgICAgIC50cmltKCksCiAgICAgICAgaW5mb3JtYXRpb246IGRldGFpbHMuaW5mb3JtYXRpb25Db2xsZWN0b3I/LmNhbGwoKSA/PyBjb25zdCBbXSwKICAgICAgICBwcmludERldGFpbHM6IGZhbHNlLAogICAgICAgIGZhdGFsOiBmYXRhbCwKICAgICAgKTsKCiAgQG92ZXJyaWRlCiAgRnV0dXJlPHZvaWQ+IGxvZyhTdHJpbmcgbWVzc2FnZSkgPT4gX2NyYXNobHl0aWNzLmxvZyhtZXNzYWdlKTsKCiAgLy8vIFNldHMgdGhlIGlkIG9mIHRoZSB1c2VyLCBvciBjbGVhcnMgaXQgd2l0aCBgbnVsbGAsIHdoaWNoIENyYXNobHl0aWNzCiAgLy8vIGRvZXMgd2l0aCBhbiBlbXB0eSBpZC4KICBAb3ZlcnJpZGUKICBGdXR1cmU8dm9pZD4gc2V0VXNlcklkKFN0cmluZz8gdXNlcklkKSA9PgogICAgICBfY3Jhc2hseXRpY3Muc2V0VXNlcklkZW50aWZpZXIodXNlcklkID8/ICcnKTsKfQo=",
      "type": "text"
    }
  ],
  "hooks": [],
  "name": "firebase_crashlytics",
  "description":
      "The crash reporting of an SMF app with Firebase Crashlytics: the crash reporter on FirebaseCrashlytics.",
  "version": "0.1.0+1",
  "environment": {"mason": "^0.1.1"},
  "vars": {}
});
