// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, implicit_dynamic_list_literal, implicit_dynamic_map_literal, inference_failure_on_collection_literal

import 'package:mason/mason.dart';

final firebaseCrashlyticsBundle = MasonBundle.fromJson(<String, dynamic>{
  "files": [
    {
      "path": "lib/core/crash_reporting/crashlytics_crash_reporter.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmZpcmViYXNlX2NyYXNobHl0aWNzL2ZpcmViYXNlX2NyYXNobHl0aWNzLmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6Zmx1dHRlci9mb3VuZGF0aW9uLmRhcnQnOwoKaW1wb3J0ICdjcmFzaF9yZXBvcnRlci5kYXJ0JzsKCi8vLyBDcmVhdGVzIGEgY3Jhc2ggcmVwb3J0ZXIgdGhhdCByZXBvcnRzIHRvIEZpcmViYXNlIENyYXNobHl0aWNzLCB3aGljaAovLy8gbmVlZHMgRmlyZWJhc2UgdG8gYmUgaW5pdGlhbGl6ZWQuCi8vLwovLy8gVGhlIGFwcCBoYXMgb25lIGNyYXNoIHJlcG9ydGVyLCB3aGljaCBgY3JlYXRlQ3Jhc2hSZXBvcnRlcigpYCByZXR1cm5zIGFuZAovLy8gd2hpY2ggZm9yd2FyZHMgZXZlcnkgcmVwb3J0IHRvIHRoaXMgb25lLgpDcmFzaFJlcG9ydGVyIGNyZWF0ZUNyYXNobHl0aWNzQ3Jhc2hSZXBvcnRlcigpID0+CiAgICBDcmFzaGx5dGljc0NyYXNoUmVwb3J0ZXIoRmlyZWJhc2VDcmFzaGx5dGljcy5pbnN0YW5jZSk7CgovLy8gUmVwb3J0cyB0aGUgZXJyb3JzIG9mIHRoZSBhcHAgdG8gRmlyZWJhc2UgQ3Jhc2hseXRpY3MuCi8vLwovLy8gSXQgcHJpbnRzIG5vdGhpbmcuIEluIGRlYnVnIG1vZGUsIENyYXNobHl0aWNzIHByaW50cyBlYWNoIHJlcG9ydCBhbmQKLy8vIHByZXNlbnRzIGVhY2ggZXJyb3Igb2YgRmx1dHRlciwgYnV0IHRoZSBoYW5kbGVycyB0aGF0Ci8vLyBgaW5zdGFsbENyYXNoUmVwb3J0aW5nKClgIGluc3RhbGxzIGFscmVhZHkgbGVhdmUgdGhlIGVycm9ycyB0aGV5IHJlcG9ydAovLy8gaW4gdGhlIGNvbnNvbGUsIHNvIGVhY2ggd291bGQgYXBwZWFyIHR3aWNlLgpmaW5hbCBjbGFzcyBDcmFzaGx5dGljc0NyYXNoUmVwb3J0ZXIgaW1wbGVtZW50cyBDcmFzaFJlcG9ydGVyIHsKICAvLy8gQ3JlYXRlcyB0aGUgcmVwb3J0ZXIgb24gdGhlIGdpdmVuIFtGaXJlYmFzZUNyYXNobHl0aWNzXS4KICBDcmFzaGx5dGljc0NyYXNoUmVwb3J0ZXIodGhpcy5fY3Jhc2hseXRpY3MpOwoKICBmaW5hbCBGaXJlYmFzZUNyYXNobHl0aWNzIF9jcmFzaGx5dGljczsKCiAgQG92ZXJyaWRlCiAgRnV0dXJlPHZvaWQ+IHJlY29yZEVycm9yKAogICAgT2JqZWN0IGVycm9yLAogICAgU3RhY2tUcmFjZT8gc3RhY2tUcmFjZSwgewogICAgYm9vbCBmYXRhbCA9IGZhbHNlLAogICAgU3RyaW5nPyByZWFzb24sCiAgfSkgPT4KICAgICAgX2NyYXNobHl0aWNzLnJlY29yZEVycm9yKAogICAgICAgIGVycm9yLAogICAgICAgIHN0YWNrVHJhY2UsCiAgICAgICAgcmVhc29uOiByZWFzb24sCiAgICAgICAgcHJpbnREZXRhaWxzOiBmYWxzZSwKICAgICAgICBmYXRhbDogZmF0YWwsCiAgICAgICk7CgogIC8vLyBSZXBvcnRzIHdoYXQgW0ZpcmViYXNlQ3Jhc2hseXRpY3MucmVjb3JkRmx1dHRlckVycm9yXSByZXBvcnRzLCB3aXRob3V0CiAgLy8vIHByZXNlbnRpbmcgdGhlIGVycm9yIGFzIGl0IGFsc28gZG9lcy4KICBAb3ZlcnJpZGUKICBGdXR1cmU8dm9pZD4gcmVjb3JkRmx1dHRlckVycm9yKAogICAgRmx1dHRlckVycm9yRGV0YWlscyBkZXRhaWxzLCB7CiAgICBib29sIGZhdGFsID0gZmFsc2UsCiAgfSkgPT4KICAgICAgX2NyYXNobHl0aWNzLnJlY29yZEVycm9yKAogICAgICAgIGRldGFpbHMuZXhjZXB0aW9uQXNTdHJpbmcoKSwKICAgICAgICBkZXRhaWxzLnN0YWNrLAogICAgICAgIHJlYXNvbjogZGV0YWlscy5jb250ZXh0CiAgICAgICAgICAgID8udG9TdHJpbmdEZWVwKG1pbkxldmVsOiBEaWFnbm9zdGljTGV2ZWwuaW5mbykKICAgICAgICAgICAgLnRyaW0oKSwKICAgICAgICBpbmZvcm1hdGlvbjogZGV0YWlscy5pbmZvcm1hdGlvbkNvbGxlY3Rvcj8uY2FsbCgpID8/IGNvbnN0IFtdLAogICAgICAgIHByaW50RGV0YWlsczogZmFsc2UsCiAgICAgICAgZmF0YWw6IGZhdGFsLAogICAgICApOwoKICBAb3ZlcnJpZGUKICBGdXR1cmU8dm9pZD4gbG9nKFN0cmluZyBtZXNzYWdlKSA9PiBfY3Jhc2hseXRpY3MubG9nKG1lc3NhZ2UpOwoKICAvLy8gU2V0cyB0aGUgaWQgb2YgdGhlIHVzZXIsIG9yIGNsZWFycyBpdCB3aXRoIGBudWxsYCwgd2hpY2ggQ3Jhc2hseXRpY3MKICAvLy8gZG9lcyB3aXRoIGFuIGVtcHR5IGlkLgogIEBvdmVycmlkZQogIEZ1dHVyZTx2b2lkPiBzZXRVc2VySWQoU3RyaW5nPyB1c2VySWQpID0+CiAgICAgIF9jcmFzaGx5dGljcy5zZXRVc2VySWRlbnRpZmllcih1c2VySWQgPz8gJycpOwp9Cg==",
      "type": "text"
    }
  ],
  "hooks": [],
  "name": "firebase_crashlytics",
  "description":
      "The crash reporting of an SMF app with Firebase Crashlytics: the crash reporter on FirebaseCrashlytics.",
  "version": "0.1.0+1",
  "environment": {"mason": "^0.1.1"},
  "vars": {}
});
