name: {{app_name}}
description: "A new Flutter project."
publish_to: none
version: 1.0.0+1

{{{smf_pubspec_environment}}}

{{{smf_pubspec_dependencies}}}

{{{smf_pubspec_dev_dependencies}}}

{{{smf_pubspec_flutter}}}
