// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, implicit_dynamic_list_literal, implicit_dynamic_map_literal, inference_failure_on_collection_literal

import 'package:mason/mason.dart';

final firebaseAnalyticsBundle = MasonBundle.fromJson(<String, dynamic>{
  "files": [
    {
      "path": "lib/core/analytics/firebase_analytics_service.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmZpcmViYXNlX2FuYWx5dGljcy9maXJlYmFzZV9hbmFseXRpY3MuZGFydCc7Cnt7I2hhc19yb3V0ZXJ9fWltcG9ydCAncGFja2FnZTpmbHV0dGVyL2ZvdW5kYXRpb24uZGFydCcgc2hvdyBkZWJ1Z1ByaW50OwppbXBvcnQgJ3BhY2thZ2U6Zmx1dHRlci9zZXJ2aWNlcy5kYXJ0JyBzaG93IFBsYXRmb3JtRXhjZXB0aW9uOwp7ey9oYXNfcm91dGVyfX0KaW1wb3J0ICdhbmFseXRpY3Nfc2VydmljZS5kYXJ0JzsKCi8vLyBDcmVhdGVzIGFuIGFuYWx5dGljcyBzZXJ2aWNlIHRoYXQgcmVjb3JkcyB0byBGaXJlYmFzZSBBbmFseXRpY3MsIHdoaWNoCi8vLyBuZWVkcyBGaXJlYmFzZSB0byBiZSBpbml0aWFsaXplZC4KLy8vCi8vLyBUaGUgYXBwIGhhcyBvbmUgYW5hbHl0aWNzIHNlcnZpY2UsIHdoaWNoIGBjcmVhdGVBbmFseXRpY3NTZXJ2aWNlKClgCi8vLyByZXR1cm5zIGFuZCB3aGljaCBmb3J3YXJkcyBldmVyeSBjYWxsIHRvIHRoaXMgb25lLgpBbmFseXRpY3NTZXJ2aWNlIGNyZWF0ZUZpcmViYXNlQW5hbHl0aWNzU2VydmljZSgpID0+CiAgICBGaXJlYmFzZUFuYWx5dGljc1NlcnZpY2UoRmlyZWJhc2VBbmFseXRpY3MuaW5zdGFuY2UpOwoKLy8vIFJlY29yZHMgd2hhdCB1c2VycyBkbyBpbiB0aGUgYXBwIHdpdGggRmlyZWJhc2UgQW5hbHl0aWNzLgovLy8KLy8vIEEgc2lnbi1pbiBhbmQgYSBzaWduLXVwIGFyZSB0aGUgc3RhbmRhcmQgYGxvZ2luYCBhbmQgYHNpZ25fdXBgIGV2ZW50cyBvZgovLy8gRmlyZWJhc2UgQW5hbHl0aWNzLCB3aXRoIHRoZSBtZXRob2QgaW4gdGhlaXIgYG1ldGhvZGAgcGFyYW1ldGVyLgpmaW5hbCBjbGFzcyBGaXJlYmFzZUFuYWx5dGljc1NlcnZpY2UgaW1wbGVtZW50cyBBbmFseXRpY3NTZXJ2aWNlIHsKICAvLy8gQ3JlYXRlcyB0aGUgc2VydmljZSBvbiB0aGUgZ2l2ZW4gW0ZpcmViYXNlQW5hbHl0aWNzXS4KICBGaXJlYmFzZUFuYWx5dGljc1NlcnZpY2UodGhpcy5fYW5hbHl0aWNzKTsKCiAgZmluYWwgRmlyZWJhc2VBbmFseXRpY3MgX2FuYWx5dGljczsKCiAgQG92ZXJyaWRlCiAgRnV0dXJlPHZvaWQ+IGxvZ0V2ZW50KFN0cmluZyBuYW1lLCB7TWFwPFN0cmluZywgT2JqZWN0Pj8gcGFyYW1ldGVyc30pID0+CiAgICAgIF9hbmFseXRpY3MubG9nRXZlbnQobmFtZTogbmFtZSwgcGFyYW1ldGVyczogcGFyYW1ldGVycyk7CgogIEBvdmVycmlkZQogIEZ1dHVyZTx2b2lkPiBsb2dTaWduSW4oe1N0cmluZz8gbWV0aG9kLCBNYXA8U3RyaW5nLCBPYmplY3Q+PyBwYXJhbWV0ZXJzfSkgPT4KICAgICAgX2FuYWx5dGljcy5sb2dMb2dpbihsb2dpbk1ldGhvZDogbWV0aG9kLCBwYXJhbWV0ZXJzOiBwYXJhbWV0ZXJzKTsKCiAgQG92ZXJyaWRlCiAgRnV0dXJlPHZvaWQ+IGxvZ1NpZ25VcCh7CiAgICByZXF1aXJlZCBTdHJpbmcgbWV0aG9kLAogICAgTWFwPFN0cmluZywgT2JqZWN0Pj8gcGFyYW1ldGVycywKICB9KSA9PgogICAgICBfYW5hbHl0aWNzLmxvZ1NpZ25VcChzaWduVXBNZXRob2Q6IG1ldGhvZCwgcGFyYW1ldGVyczogcGFyYW1ldGVycyk7CgogIEBvdmVycmlkZQogIEZ1dHVyZTx2b2lkPiBzZXRBbmFseXRpY3NDb2xsZWN0aW9uRW5hYmxlZChib29sIGVuYWJsZWQpID0+CiAgICAgIF9hbmFseXRpY3Muc2V0QW5hbHl0aWNzQ29sbGVjdGlvbkVuYWJsZWQoZW5hYmxlZCk7CgogIEBvdmVycmlkZQogIEZ1dHVyZTx2b2lkPiBzZXRVc2VySWQoU3RyaW5nPyB1c2VySWQpID0+IF9hbmFseXRpY3Muc2V0VXNlcklkKGlkOiB1c2VySWQpOwoKICBAb3ZlcnJpZGUKICBGdXR1cmU8dm9pZD4gc2V0VXNlclByb3BlcnR5KHsKICAgIHJlcXVpcmVkIFN0cmluZyBuYW1lLAogICAgcmVxdWlyZWQgU3RyaW5nPyB2YWx1ZSwKICB9KSA9PgogICAgICBfYW5hbHl0aWNzLnNldFVzZXJQcm9wZXJ0eShuYW1lOiBuYW1lLCB2YWx1ZTogdmFsdWUpOwp9e3sjaGFzX3JvdXRlcn19CgovLy8gTG9ncyBhIHNjcmVlbiB2aWV3IHRvIEZpcmViYXNlIEFuYWx5dGljcyBmb3IgdGhlIHNjcmVlbiB0aGUgdXNlciBzZWVzLAovLy8gd2hpY2ggdGhlIHJvdXRlciBvZiB0aGUgYXBwIHRlbGxzIGl0IGFib3V0OiB0aGUgZnVsbCBuYW1lIG9mIGl0cyByb3V0ZSwKLy8vIHN1Y2ggYXMgYGhvbWUuaG9tZWAsIG9yLCBmb3IgYSBzY3JlZW4gdGhhdCBpcyBubyByb3V0ZSBvZiBhIG1vZHVsZSwgdGhlCi8vLyBwYXRoIG9mIGl0cyBsb2NhdGlvbiwgd2l0aG91dCB0aGUgcXVlcnksIHdoaWNoIG1heSBob2xkIGFueXRoaW5nIGZvciBhCi8vLyBsb2NhdGlvbiB0aGF0IHRoZSBhcHAgY2Fubm90IHNob3cuCi8vLwovLy8gTm90aGluZyB3YWl0cyBmb3IgdGhlIHNjcmVlbiB2aWV3LCBzbyBhbiBlcnJvciBvZiB0aGUgcGxhdGZvcm0gaXMKLy8vIHByaW50ZWQgcmF0aGVyIHRoYW4gbGVmdCB0byB0aGUgaGFuZGxlciBvZiB0aGUgdW5jYXVnaHQgZXJyb3JzIG9mIHRoZQovLy8gYXBwLgp2b2lkIGxvZ0ZpcmViYXNlU2NyZWVuVmlldyhTdHJpbmc/IHJvdXRlLCBTdHJpbmcgbG9jYXRpb24pIHsKICBGaXJlYmFzZUFuYWx5dGljcy5pbnN0YW5jZQogICAgICAubG9nU2NyZWVuVmlldyhzY3JlZW5OYW1lOiByb3V0ZSA/PyBVcmkucGFyc2UobG9jYXRpb24pLnBhdGgpCiAgICAgIC5jYXRjaEVycm9yKAogICAgICAgIChPYmplY3QgZXJyb3IpID0+IGRlYnVnUHJpbnQoJ0ZpcmViYXNlIEFuYWx5dGljczogJGVycm9yJyksCiAgICAgICAgdGVzdDogKGVycm9yKSA9PiBlcnJvciBpcyBQbGF0Zm9ybUV4Y2VwdGlvbiwKICAgICAgKTsKfXt7L2hhc19yb3V0ZXJ9fQo=",
      "type": "text"
    }
  ],
  "hooks": [],
  "name": "firebase_analytics",
  "description":
      "The analytics of an SMF app with Firebase Analytics: the analytics service on FirebaseAnalytics.",
  "version": "0.1.0+1",
  "environment": {"mason": "^0.1.1"},
  "vars": {}
});
