// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, implicit_dynamic_list_literal, implicit_dynamic_map_literal, inference_failure_on_collection_literal

import 'package:mason/mason.dart';

final firebaseAnalyticsBundle = MasonBundle.fromJson(<String, dynamic>{
  "files": [
    {
      "path": "lib/core/analytics/firebase_analytics_service.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmZpcmViYXNlX2FuYWx5dGljcy9maXJlYmFzZV9hbmFseXRpY3MuZGFydCc7CgppbXBvcnQgJ2FuYWx5dGljc19zZXJ2aWNlLmRhcnQnOwoKLy8vIENyZWF0ZXMgYW4gYW5hbHl0aWNzIHNlcnZpY2UgdGhhdCByZWNvcmRzIHRvIEZpcmViYXNlIEFuYWx5dGljcywgd2hpY2gKLy8vIG5lZWRzIEZpcmViYXNlIHRvIGJlIGluaXRpYWxpemVkLgovLy8KLy8vIFRoZSBhcHAgaGFzIG9uZSBhbmFseXRpY3Mgc2VydmljZSwgd2hpY2ggYGNyZWF0ZUFuYWx5dGljc1NlcnZpY2UoKWAKLy8vIHJldHVybnMgYW5kIHdoaWNoIGZvcndhcmRzIGV2ZXJ5IGNhbGwgdG8gdGhpcyBvbmUuCkFuYWx5dGljc1NlcnZpY2UgY3JlYXRlRmlyZWJhc2VBbmFseXRpY3NTZXJ2aWNlKCkgPT4KICAgIEZpcmViYXNlQW5hbHl0aWNzU2VydmljZShGaXJlYmFzZUFuYWx5dGljcy5pbnN0YW5jZSk7CgovLy8gUmVjb3JkcyB3aGF0IHVzZXJzIGRvIGluIHRoZSBhcHAgd2l0aCBGaXJlYmFzZSBBbmFseXRpY3MuCi8vLwovLy8gQSBzaWduLWluIGFuZCBhIHNpZ24tdXAgYXJlIHRoZSBzdGFuZGFyZCBgbG9naW5gIGFuZCBgc2lnbl91cGAgZXZlbnRzIG9mCi8vLyBGaXJlYmFzZSBBbmFseXRpY3MsIHdpdGggdGhlIG1ldGhvZCBpbiB0aGVpciBgbWV0aG9kYCBwYXJhbWV0ZXIuCmZpbmFsIGNsYXNzIEZpcmViYXNlQW5hbHl0aWNzU2VydmljZSBpbXBsZW1lbnRzIEFuYWx5dGljc1NlcnZpY2UgewogIC8vLyBDcmVhdGVzIHRoZSBzZXJ2aWNlIG9uIHRoZSBnaXZlbiBbRmlyZWJhc2VBbmFseXRpY3NdLgogIEZpcmViYXNlQW5hbHl0aWNzU2VydmljZSh0aGlzLl9hbmFseXRpY3MpOwoKICBmaW5hbCBGaXJlYmFzZUFuYWx5dGljcyBfYW5hbHl0aWNzOwoKICBAb3ZlcnJpZGUKICBGdXR1cmU8dm9pZD4gbG9nRXZlbnQoU3RyaW5nIG5hbWUsIHtNYXA8U3RyaW5nLCBPYmplY3Q+PyBwYXJhbWV0ZXJzfSkgPT4KICAgICAgX2FuYWx5dGljcy5sb2dFdmVudChuYW1lOiBuYW1lLCBwYXJhbWV0ZXJzOiBwYXJhbWV0ZXJzKTsKCiAgQG92ZXJyaWRlCiAgRnV0dXJlPHZvaWQ+IGxvZ1NpZ25Jbih7U3RyaW5nPyBtZXRob2QsIE1hcDxTdHJpbmcsIE9iamVjdD4/IHBhcmFtZXRlcnN9KSA9PgogICAgICBfYW5hbHl0aWNzLmxvZ0xvZ2luKGxvZ2luTWV0aG9kOiBtZXRob2QsIHBhcmFtZXRlcnM6IHBhcmFtZXRlcnMpOwoKICBAb3ZlcnJpZGUKICBGdXR1cmU8dm9pZD4gbG9nU2lnblVwKHsKICAgIHJlcXVpcmVkIFN0cmluZyBtZXRob2QsCiAgICBNYXA8U3RyaW5nLCBPYmplY3Q+PyBwYXJhbWV0ZXJzLAogIH0pID0+CiAgICAgIF9hbmFseXRpY3MubG9nU2lnblVwKHNpZ25VcE1ldGhvZDogbWV0aG9kLCBwYXJhbWV0ZXJzOiBwYXJhbWV0ZXJzKTsKCiAgQG92ZXJyaWRlCiAgRnV0dXJlPHZvaWQ+IHNldEFuYWx5dGljc0NvbGxlY3Rpb25FbmFibGVkKGJvb2wgZW5hYmxlZCkgPT4KICAgICAgX2FuYWx5dGljcy5zZXRBbmFseXRpY3NDb2xsZWN0aW9uRW5hYmxlZChlbmFibGVkKTsKCiAgQG92ZXJyaWRlCiAgRnV0dXJlPHZvaWQ+IHNldFVzZXJJZChTdHJpbmc/IHVzZXJJZCkgPT4gX2FuYWx5dGljcy5zZXRVc2VySWQoaWQ6IHVzZXJJZCk7CgogIEBvdmVycmlkZQogIEZ1dHVyZTx2b2lkPiBzZXRVc2VyUHJvcGVydHkoewogICAgcmVxdWlyZWQgU3RyaW5nIG5hbWUsCiAgICByZXF1aXJlZCBTdHJpbmc/IHZhbHVlLAogIH0pID0+CiAgICAgIF9hbmFseXRpY3Muc2V0VXNlclByb3BlcnR5KG5hbWU6IG5hbWUsIHZhbHVlOiB2YWx1ZSk7Cn0K",
      "type": "text"
    }
  ],
  "hooks": [],
  "name": "firebase_analytics",
  "description":
      "The analytics of an SMF app with Firebase Analytics: the analytics service on FirebaseAnalytics.",
  "version": "0.1.0+1",
  "environment": {"mason": "^0.1.1"},
  "vars": {}
});
