/// Sample sources shared by the contribution engine tests.
library;

/// `lib/main.dart` as generated by the smf_flutter_monolith_core brick.
const monolithMainDart = '''
import 'package:flutter/material.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(body: Center(child: Text('Hello World!'))),
    );
  }
}
''';

/// `lib/main.dart` as generated by the smf_flutter_riverpod brick.
const riverpodMainDart = '''
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(const ProviderScope(child: MainApp()));
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(body: Center(child: Text('Hello World!'))),
    );
  }
}
''';

/// The part of [monolithMainDart] that follows `main()`.
final monolithMainAppClass = monolithMainDart.substring(
  monolithMainDart.indexOf('class MainApp'),
);

/// A `main()` that registers app-wide services through `MultiProvider`.
const providerMainDart = '''
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() {
  runApp(
    MultiProvider(
      providers: [
        Provider(create: (_) => Logger()),
      ],
      child: const MainApp(),
    ),
  );
}
''';

/// A `State` class with lifecycle methods.
const homePageStateDart = '''
import 'package:flutter/material.dart';

class _HomePageState extends State<HomePage>
    with SingleTickerProviderStateMixin {
  late final AnimationController _controller;

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => const SizedBox();
}
''';
