name: {{app_name.snakeCase()}}
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  {{#dependencies}}
  {{{.}}}
  {{/dependencies}}

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  {{#dev_dependencies}}
  {{{.}}}
  {{/dev_dependencies}}

flutter:
  uses-material-design: true
