// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, implicit_dynamic_list_literal, implicit_dynamic_map_literal, inference_failure_on_collection_literal

import 'package:mason/mason.dart';

final firebaseCoreBundle = MasonBundle.fromJson(<String, dynamic>{
  "files": [
    {
      "path": "lib/firebase_options.dart",
      "data":
          "Ly8gRmlsZSBnZW5lcmF0ZWQgYnkgRmx1dHRlckZpcmUgQ0xJLgovLyBpZ25vcmVfZm9yX2ZpbGU6IHR5cGU9bGludAppbXBvcnQgJ3BhY2thZ2U6ZmlyZWJhc2VfY29yZS9maXJlYmFzZV9jb3JlLmRhcnQnIHNob3cgRmlyZWJhc2VPcHRpb25zOwppbXBvcnQgJ3BhY2thZ2U6Zmx1dHRlci9mb3VuZGF0aW9uLmRhcnQnCiAgICBzaG93IGRlZmF1bHRUYXJnZXRQbGF0Zm9ybSwga0lzV2ViLCBUYXJnZXRQbGF0Zm9ybTsKCi8vLyBEZWZhdWx0IFtGaXJlYmFzZU9wdGlvbnNdIGZvciB1c2Ugd2l0aCB5b3VyIEZpcmViYXNlIGFwcHMuCi8vLwovLy8gRXhhbXBsZToKLy8vIGBgYGRhcnQKLy8vIGltcG9ydCAnZmlyZWJhc2Vfb3B0aW9ucy5kYXJ0JzsKLy8vIC8vIC4uLgovLy8gYXdhaXQgRmlyZWJhc2UuaW5pdGlhbGl6ZUFwcCgKLy8vICAgb3B0aW9uczogRGVmYXVsdEZpcmViYXNlT3B0aW9ucy5jdXJyZW50UGxhdGZvcm0sCi8vLyApOwovLy8gYGBgCmNsYXNzIERlZmF1bHRGaXJlYmFzZU9wdGlvbnMgewogIHN0YXRpYyBGaXJlYmFzZU9wdGlvbnMgZ2V0IGN1cnJlbnRQbGF0Zm9ybSB7CiAgICBpZiAoa0lzV2ViKSB7CiAgICAgIHRocm93IFVuc3VwcG9ydGVkRXJyb3IoCiAgICAgICAgJ0RlZmF1bHRGaXJlYmFzZU9wdGlvbnMgaGF2ZSBub3QgYmVlbiBjb25maWd1cmVkIGZvciB3ZWIgLSAnCiAgICAgICAgJ3lvdSBjYW4gcmVjb25maWd1cmUgdGhpcyBieSBydW5uaW5nIHRoZSBGbHV0dGVyRmlyZSBDTEkgYWdhaW4uJywKICAgICAgKTsKICAgIH0KICAgIHN3aXRjaCAoZGVmYXVsdFRhcmdldFBsYXRmb3JtKSB7CiAgICAgIGNhc2UgVGFyZ2V0UGxhdGZvcm0uYW5kcm9pZDoKICAgICAgICB0aHJvdyBVbnN1cHBvcnRlZEVycm9yKAogICAgICAgICAgJ0RlZmF1bHRGaXJlYmFzZU9wdGlvbnMgaGF2ZSBub3QgYmVlbiBjb25maWd1cmVkIGZvciBhbmRyb2lkIC0gJwogICAgICAgICAgJ3lvdSBjYW4gcmVjb25maWd1cmUgdGhpcyBieSBydW5uaW5nIHRoZSBGbHV0dGVyRmlyZSBDTEkgYWdhaW4uJywKICAgICAgICApOwogICAgICBjYXNlIFRhcmdldFBsYXRmb3JtLmlPUzoKICAgICAgICB0aHJvdyBVbnN1cHBvcnRlZEVycm9yKAogICAgICAgICAgJ0RlZmF1bHRGaXJlYmFzZU9wdGlvbnMgaGF2ZSBub3QgYmVlbiBjb25maWd1cmVkIGZvciBpb3MgLSAnCiAgICAgICAgICAneW91IGNhbiByZWNvbmZpZ3VyZSB0aGlzIGJ5IHJ1bm5pbmcgdGhlIEZsdXR0ZXJGaXJlIENMSSBhZ2Fpbi4nLAogICAgICAgICk7CiAgICAgIGNhc2UgVGFyZ2V0UGxhdGZvcm0ubWFjT1M6CiAgICAgICAgdGhyb3cgVW5zdXBwb3J0ZWRFcnJvcigKICAgICAgICAgICdEZWZhdWx0RmlyZWJhc2VPcHRpb25zIGhhdmUgbm90IGJlZW4gY29uZmlndXJlZCBmb3IgbWFjb3MgLSAnCiAgICAgICAgICAneW91IGNhbiByZWNvbmZpZ3VyZSB0aGlzIGJ5IHJ1bm5pbmcgdGhlIEZsdXR0ZXJGaXJlIENMSSBhZ2Fpbi4nLAogICAgICAgICk7CiAgICAgIGNhc2UgVGFyZ2V0UGxhdGZvcm0ud2luZG93czoKICAgICAgICB0aHJvdyBVbnN1cHBvcnRlZEVycm9yKAogICAgICAgICAgJ0RlZmF1bHRGaXJlYmFzZU9wdGlvbnMgaGF2ZSBub3QgYmVlbiBjb25maWd1cmVkIGZvciB3aW5kb3dzIC0gJwogICAgICAgICAgJ3lvdSBjYW4gcmVjb25maWd1cmUgdGhpcyBieSBydW5uaW5nIHRoZSBGbHV0dGVyRmlyZSBDTEkgYWdhaW4uJywKICAgICAgICApOwogICAgICBjYXNlIFRhcmdldFBsYXRmb3JtLmxpbnV4OgogICAgICAgIHRocm93IFVuc3VwcG9ydGVkRXJyb3IoCiAgICAgICAgICAnRGVmYXVsdEZpcmViYXNlT3B0aW9ucyBoYXZlIG5vdCBiZWVuIGNvbmZpZ3VyZWQgZm9yIGxpbnV4IC0gJwogICAgICAgICAgJ3lvdSBjYW4gcmVjb25maWd1cmUgdGhpcyBieSBydW5uaW5nIHRoZSBGbHV0dGVyRmlyZSBDTEkgYWdhaW4uJywKICAgICAgICApOwogICAgICBkZWZhdWx0OgogICAgICAgIHRocm93IFVuc3VwcG9ydGVkRXJyb3IoCiAgICAgICAgICAnRGVmYXVsdEZpcmViYXNlT3B0aW9ucyBhcmUgbm90IHN1cHBvcnRlZCBmb3IgdGhpcyBwbGF0Zm9ybS4nLAogICAgICAgICk7CiAgICB9CiAgfQp9Cg==",
      "type": "text"
    }
  ],
  "hooks": [],
  "name": "firebase_core",
  "description":
      "Firebase in an SMF app: the options of its Firebase apps, a placeholder until flutterfire configure writes them.",
  "version": "0.1.0+1",
  "environment": {"mason": "^0.1.1"},
  "vars": {}
});
