// Writes the smf_flutter_cli version from its pubspec.yaml into
// lib/version.dart. Runs as the `melos version` preCommit hook, so the
// version printed by `smf --version` always matches the released package.
import 'dart:io';

void main() {
  const packageDir = 'packages/smf_flutter_cli';
  final pubspec = File('$packageDir/pubspec.yaml').readAsStringSync();
  final match = RegExp(r'^version:\s*(\S+)', multiLine: true).firstMatch(
    pubspec,
  );
  if (match == null) {
    stderr.writeln('No version found in $packageDir/pubspec.yaml');
    exit(1);
  }

  final version = match.group(1)!;
  File('$packageDir/lib/version.dart').writeAsStringSync('''
// Generated by tools/sync_cli_version.dart. Do not modify.
// This file provides the CLI version string without parsing pubspec.

/// The current version of the SMF Flutter CLI.
const packageVersion = '$version';
''');
  stdout.writeln('lib/version.dart -> $version');
}
