name: smf_flutter_cli
description: "CLI for SayMyFrame (SMF) Flutter: scaffold projects, configure modules, and generate code."
version: 0.1.0
homepage: https://saymyframe.com
repository: https://github.com/saymyframe/smf_flutter_cli
issue_tracker: https://github.com/saymyframe/smf_flutter_cli/issues
topics: [flutter, cli, scaffolding, configuration, code-generation]
license: Apache-2.0

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  smf: smf_flutter

dependencies:
  ansi_styles: ^0.3.2+1
  args: ^2.7.0
  cli_util: ^0.4.2
  file: ^7.0.1
  interact: ^2.2.0
  mason: ^0.1.1
  meta: ^1.17.0
  path: ^1.9.1
  yaml_edit: ^2.2.2

  # Packages
  smf_contribution_engine: ^0.1.0
  smf_contracts: ^0.1.0
  smf_event_bus: ^0.1.0
  smf_firebase_analytics: ^0.1.0
  smf_firebase_core: ^0.1.0
  smf_flutter_core: ^0.1.0
  smf_get_it: ^0.1.0
  smf_go_router: ^0.1.0
  smf_home_flutter: ^0.1.0

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^9.0.0

