name: smf_flutter_cli
description: A sample command-line application with basic argument parsing.
version: 0.1.0
homepage: https://saymyframe.com
repository: https://github.com/saymyframe/smf_flutter_cli
issue_tracker: https://github.com/saymyframe/smf_flutter_cli/issues
topics: [flutter, cli, scaffolding, configuration, code-generation]
license: Apache-2.0

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  smfflutter: smf_flutter

dependencies:
  ansi_styles: ^0.3.2+1
  args: ^2.7.0
  cli_util: ^0.4.2
  file: ^7.0.1
  interact: ^2.2.0
  mason: ^0.1.1
  meta: ^1.17.0
  path: ^1.9.1
  yaml_edit: ^2.2.2

  # Packages
  smf_firebase_core:
    path: ../smf_modules/smf_firebase_core
  smf_flutter_core:
    path: ../smf_modules/smf_flutter_core
  smf_analytics:
    path: ../smf_modules/smf_analytics
  smf_contracts:
    path: ../smf_contracts
  smf_get_it:
    path: ../smf_modules/smf_get_it
  smf_communication:
    path: ../smf_modules/smf_communication
  smf_contribution_engine:
    path: ../smf_modules/smf_contribution_engine
  smf_go_router:
    path: ../smf_modules/smf_go_router
  smf_home_flutter:
    path: ../smf_modules/smf_home_flutter

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^9.0.0

